// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/management/device.proto

package ai.sensorycloud.api.v1.management;

/**
 * <pre>
 * Request to renew a device's credential
 * </pre>
 *
 * Protobuf type {@code sensory.api.v1.management.RenewDeviceCredentialRequest}
 */
public  final class RenewDeviceCredentialRequest extends
    com.google.protobuf.GeneratedMessageLite<
        RenewDeviceCredentialRequest, RenewDeviceCredentialRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:sensory.api.v1.management.RenewDeviceCredentialRequest)
    RenewDeviceCredentialRequestOrBuilder {
  private RenewDeviceCredentialRequest() {
    deviceId_ = "";
    clientId_ = "";
    tenantId_ = "";
    credential_ = "";
  }
  public static final int DEVICEID_FIELD_NUMBER = 1;
  private java.lang.String deviceId_;
  /**
   * <pre>
   * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
   * A typical value would be a hardware serial number.
   * </pre>
   *
   * <code>string deviceId = 1 [(.validate.rules) = { ... }</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    return deviceId_;
  }
  /**
   * <pre>
   * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
   * A typical value would be a hardware serial number.
   * </pre>
   *
   * <code>string deviceId = 1 [(.validate.rules) = { ... }</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
  }
  /**
   * <pre>
   * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
   * A typical value would be a hardware serial number.
   * </pre>
   *
   * <code>string deviceId = 1 [(.validate.rules) = { ... }</code>
   * @param value The deviceId to set.
   */
  private void setDeviceId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    deviceId_ = value;
  }
  /**
   * <pre>
   * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
   * A typical value would be a hardware serial number.
   * </pre>
   *
   * <code>string deviceId = 1 [(.validate.rules) = { ... }</code>
   */
  private void clearDeviceId() {
    
    deviceId_ = getDefaultInstance().getDeviceId();
  }
  /**
   * <pre>
   * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
   * A typical value would be a hardware serial number.
   * </pre>
   *
   * <code>string deviceId = 1 [(.validate.rules) = { ... }</code>
   * @param value The bytes for deviceId to set.
   */
  private void setDeviceIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deviceId_ = value.toStringUtf8();
    
  }

  public static final int CLIENTID_FIELD_NUMBER = 2;
  private java.lang.String clientId_;
  /**
   * <pre>
   * Unique Client ID as UUID
   * </pre>
   *
   * <code>string clientId = 2 [(.validate.rules) = { ... }</code>
   * @return The clientId.
   */
  @java.lang.Override
  public java.lang.String getClientId() {
    return clientId_;
  }
  /**
   * <pre>
   * Unique Client ID as UUID
   * </pre>
   *
   * <code>string clientId = 2 [(.validate.rules) = { ... }</code>
   * @return The bytes for clientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(clientId_);
  }
  /**
   * <pre>
   * Unique Client ID as UUID
   * </pre>
   *
   * <code>string clientId = 2 [(.validate.rules) = { ... }</code>
   * @param value The clientId to set.
   */
  private void setClientId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    clientId_ = value;
  }
  /**
   * <pre>
   * Unique Client ID as UUID
   * </pre>
   *
   * <code>string clientId = 2 [(.validate.rules) = { ... }</code>
   */
  private void clearClientId() {
    
    clientId_ = getDefaultInstance().getClientId();
  }
  /**
   * <pre>
   * Unique Client ID as UUID
   * </pre>
   *
   * <code>string clientId = 2 [(.validate.rules) = { ... }</code>
   * @param value The bytes for clientId to set.
   */
  private void setClientIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    clientId_ = value.toStringUtf8();
    
  }

  public static final int TENANTID_FIELD_NUMBER = 3;
  private java.lang.String tenantId_;
  /**
   * <pre>
   * Unique Tenant ID as UUID
   * </pre>
   *
   * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    return tenantId_;
  }
  /**
   * <pre>
   * Unique Tenant ID as UUID
   * </pre>
   *
   * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(tenantId_);
  }
  /**
   * <pre>
   * Unique Tenant ID as UUID
   * </pre>
   *
   * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
   * @param value The tenantId to set.
   */
  private void setTenantId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    tenantId_ = value;
  }
  /**
   * <pre>
   * Unique Tenant ID as UUID
   * </pre>
   *
   * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
   */
  private void clearTenantId() {
    
    tenantId_ = getDefaultInstance().getTenantId();
  }
  /**
   * <pre>
   * Unique Tenant ID as UUID
   * </pre>
   *
   * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
   * @param value The bytes for tenantId to set.
   */
  private void setTenantIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    tenantId_ = value.toStringUtf8();
    
  }

  public static final int CREDENTIAL_FIELD_NUMBER = 4;
  private java.lang.String credential_;
  /**
   * <pre>
   * The credential to be validated by the server upon enrollment.
   * Possible values are a shared secret or signed JWT.
   * </pre>
   *
   * <code>string credential = 4 [(.validate.rules) = { ... }</code>
   * @return The credential.
   */
  @java.lang.Override
  public java.lang.String getCredential() {
    return credential_;
  }
  /**
   * <pre>
   * The credential to be validated by the server upon enrollment.
   * Possible values are a shared secret or signed JWT.
   * </pre>
   *
   * <code>string credential = 4 [(.validate.rules) = { ... }</code>
   * @return The bytes for credential.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCredentialBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(credential_);
  }
  /**
   * <pre>
   * The credential to be validated by the server upon enrollment.
   * Possible values are a shared secret or signed JWT.
   * </pre>
   *
   * <code>string credential = 4 [(.validate.rules) = { ... }</code>
   * @param value The credential to set.
   */
  private void setCredential(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    credential_ = value;
  }
  /**
   * <pre>
   * The credential to be validated by the server upon enrollment.
   * Possible values are a shared secret or signed JWT.
   * </pre>
   *
   * <code>string credential = 4 [(.validate.rules) = { ... }</code>
   */
  private void clearCredential() {
    
    credential_ = getDefaultInstance().getCredential();
  }
  /**
   * <pre>
   * The credential to be validated by the server upon enrollment.
   * Possible values are a shared secret or signed JWT.
   * </pre>
   *
   * <code>string credential = 4 [(.validate.rules) = { ... }</code>
   * @param value The bytes for credential to set.
   */
  private void setCredentialBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    credential_ = value.toStringUtf8();
    
  }

  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Request to renew a device's credential
   * </pre>
   *
   * Protobuf type {@code sensory.api.v1.management.RenewDeviceCredentialRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.v1.management.RenewDeviceCredentialRequest)
      ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequestOrBuilder {
    // Construct using ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
     * A typical value would be a hardware serial number.
     * </pre>
     *
     * <code>string deviceId = 1 [(.validate.rules) = { ... }</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <pre>
     * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
     * A typical value would be a hardware serial number.
     * </pre>
     *
     * <code>string deviceId = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return instance.getDeviceIdBytes();
    }
    /**
     * <pre>
     * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
     * A typical value would be a hardware serial number.
     * </pre>
     *
     * <code>string deviceId = 1 [(.validate.rules) = { ... }</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <pre>
     * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
     * A typical value would be a hardware serial number.
     * </pre>
     *
     * <code>string deviceId = 1 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }
    /**
     * <pre>
     * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
     * A typical value would be a hardware serial number.
     * </pre>
     *
     * <code>string deviceId = 1 [(.validate.rules) = { ... }</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Unique Client ID as UUID
     * </pre>
     *
     * <code>string clientId = 2 [(.validate.rules) = { ... }</code>
     * @return The clientId.
     */
    @java.lang.Override
    public java.lang.String getClientId() {
      return instance.getClientId();
    }
    /**
     * <pre>
     * Unique Client ID as UUID
     * </pre>
     *
     * <code>string clientId = 2 [(.validate.rules) = { ... }</code>
     * @return The bytes for clientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      return instance.getClientIdBytes();
    }
    /**
     * <pre>
     * Unique Client ID as UUID
     * </pre>
     *
     * <code>string clientId = 2 [(.validate.rules) = { ... }</code>
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(
        java.lang.String value) {
      copyOnWrite();
      instance.setClientId(value);
      return this;
    }
    /**
     * <pre>
     * Unique Client ID as UUID
     * </pre>
     *
     * <code>string clientId = 2 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      copyOnWrite();
      instance.clearClientId();
      return this;
    }
    /**
     * <pre>
     * Unique Client ID as UUID
     * </pre>
     *
     * <code>string clientId = 2 [(.validate.rules) = { ... }</code>
     * @param value The bytes for clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Unique Tenant ID as UUID
     * </pre>
     *
     * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public java.lang.String getTenantId() {
      return instance.getTenantId();
    }
    /**
     * <pre>
     * Unique Tenant ID as UUID
     * </pre>
     *
     * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for tenantId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      return instance.getTenantIdBytes();
    }
    /**
     * <pre>
     * Unique Tenant ID as UUID
     * </pre>
     *
     * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTenantId(value);
      return this;
    }
    /**
     * <pre>
     * Unique Tenant ID as UUID
     * </pre>
     *
     * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      copyOnWrite();
      instance.clearTenantId();
      return this;
    }
    /**
     * <pre>
     * Unique Tenant ID as UUID
     * </pre>
     *
     * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTenantIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * The credential to be validated by the server upon enrollment.
     * Possible values are a shared secret or signed JWT.
     * </pre>
     *
     * <code>string credential = 4 [(.validate.rules) = { ... }</code>
     * @return The credential.
     */
    @java.lang.Override
    public java.lang.String getCredential() {
      return instance.getCredential();
    }
    /**
     * <pre>
     * The credential to be validated by the server upon enrollment.
     * Possible values are a shared secret or signed JWT.
     * </pre>
     *
     * <code>string credential = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for credential.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCredentialBytes() {
      return instance.getCredentialBytes();
    }
    /**
     * <pre>
     * The credential to be validated by the server upon enrollment.
     * Possible values are a shared secret or signed JWT.
     * </pre>
     *
     * <code>string credential = 4 [(.validate.rules) = { ... }</code>
     * @param value The credential to set.
     * @return This builder for chaining.
     */
    public Builder setCredential(
        java.lang.String value) {
      copyOnWrite();
      instance.setCredential(value);
      return this;
    }
    /**
     * <pre>
     * The credential to be validated by the server upon enrollment.
     * Possible values are a shared secret or signed JWT.
     * </pre>
     *
     * <code>string credential = 4 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearCredential() {
      copyOnWrite();
      instance.clearCredential();
      return this;
    }
    /**
     * <pre>
     * The credential to be validated by the server upon enrollment.
     * Possible values are a shared secret or signed JWT.
     * </pre>
     *
     * <code>string credential = 4 [(.validate.rules) = { ... }</code>
     * @param value The bytes for credential to set.
     * @return This builder for chaining.
     */
    public Builder setCredentialBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCredentialBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sensory.api.v1.management.RenewDeviceCredentialRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "deviceId_",
            "clientId_",
            "tenantId_",
            "credential_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest> parser = PARSER;
        if (parser == null) {
          synchronized (ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sensory.api.v1.management.RenewDeviceCredentialRequest)
  private static final ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest DEFAULT_INSTANCE;
  static {
    RenewDeviceCredentialRequest defaultInstance = new RenewDeviceCredentialRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RenewDeviceCredentialRequest.class, defaultInstance);
  }

  public static ai.sensorycloud.api.v1.management.RenewDeviceCredentialRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RenewDeviceCredentialRequest> PARSER;

  public static com.google.protobuf.Parser<RenewDeviceCredentialRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

