// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/event/event.proto

package ai.sensorycloud.api.v1.event;

/**
 * Protobuf type {@code sensory.api.v1.event.UsageEventResponse}
 */
public  final class UsageEventResponse extends
    com.google.protobuf.GeneratedMessageLite<
        UsageEventResponse, UsageEventResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:sensory.api.v1.event.UsageEventResponse)
    UsageEventResponseOrBuilder {
  private UsageEventResponse() {
    id_ = "";
    clientId_ = "";
    route_ = "";
    technologies_ = emptyIntList();
    models_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    billableUnits_ = "";
    tenantId_ = "";
  }
  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <pre>
   * The UTC timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <pre>
   * The UTC timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <pre>
   * The UTC timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1 [(.validate.rules) = { ... }</code>
   */
  private void setTimestamp(com.google.protobuf.Timestamp value) {
    value.getClass();
  timestamp_ = value;
    
    }
  /**
   * <pre>
   * The UTC timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1 [(.validate.rules) = { ... }</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeTimestamp(com.google.protobuf.Timestamp value) {
    value.getClass();
  if (timestamp_ != null &&
        timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      timestamp_ =
        com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
    } else {
      timestamp_ = value;
    }
    
  }
  /**
   * <pre>
   * The UTC timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1 [(.validate.rules) = { ... }</code>
   */
  private void clearTimestamp() {  timestamp_ = null;
    
  }

  public static final int DURATION_FIELD_NUMBER = 2;
  private long duration_;
  /**
   * <pre>
   * The duration of the event in milliseconds
   * </pre>
   *
   * <code>int64 duration = 2 [(.validate.rules) = { ... }</code>
   * @return The duration.
   */
  @java.lang.Override
  public long getDuration() {
    return duration_;
  }
  /**
   * <pre>
   * The duration of the event in milliseconds
   * </pre>
   *
   * <code>int64 duration = 2 [(.validate.rules) = { ... }</code>
   * @param value The duration to set.
   */
  private void setDuration(long value) {
    
    duration_ = value;
  }
  /**
   * <pre>
   * The duration of the event in milliseconds
   * </pre>
   *
   * <code>int64 duration = 2 [(.validate.rules) = { ... }</code>
   */
  private void clearDuration() {
    
    duration_ = 0L;
  }

  public static final int ID_FIELD_NUMBER = 3;
  private java.lang.String id_;
  /**
   * <pre>
   * UUID representing the unique event
   * </pre>
   *
   * <code>string id = 3 [(.validate.rules) = { ... }</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <pre>
   * UUID representing the unique event
   * </pre>
   *
   * <code>string id = 3 [(.validate.rules) = { ... }</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <pre>
   * UUID representing the unique event
   * </pre>
   *
   * <code>string id = 3 [(.validate.rules) = { ... }</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    id_ = value;
  }
  /**
   * <pre>
   * UUID representing the unique event
   * </pre>
   *
   * <code>string id = 3 [(.validate.rules) = { ... }</code>
   */
  private void clearId() {
    
    id_ = getDefaultInstance().getId();
  }
  /**
   * <pre>
   * UUID representing the unique event
   * </pre>
   *
   * <code>string id = 3 [(.validate.rules) = { ... }</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();
    
  }

  public static final int CLIENTID_FIELD_NUMBER = 4;
  private java.lang.String clientId_;
  /**
   * <pre>
   * OAuth ClientID related to the event
   * </pre>
   *
   * <code>string clientId = 4 [(.validate.rules) = { ... }</code>
   * @return The clientId.
   */
  @java.lang.Override
  public java.lang.String getClientId() {
    return clientId_;
  }
  /**
   * <pre>
   * OAuth ClientID related to the event
   * </pre>
   *
   * <code>string clientId = 4 [(.validate.rules) = { ... }</code>
   * @return The bytes for clientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(clientId_);
  }
  /**
   * <pre>
   * OAuth ClientID related to the event
   * </pre>
   *
   * <code>string clientId = 4 [(.validate.rules) = { ... }</code>
   * @param value The clientId to set.
   */
  private void setClientId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    clientId_ = value;
  }
  /**
   * <pre>
   * OAuth ClientID related to the event
   * </pre>
   *
   * <code>string clientId = 4 [(.validate.rules) = { ... }</code>
   */
  private void clearClientId() {
    
    clientId_ = getDefaultInstance().getClientId();
  }
  /**
   * <pre>
   * OAuth ClientID related to the event
   * </pre>
   *
   * <code>string clientId = 4 [(.validate.rules) = { ... }</code>
   * @param value The bytes for clientId to set.
   */
  private void setClientIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    clientId_ = value.toStringUtf8();
    
  }

  public static final int TYPE_FIELD_NUMBER = 5;
  private int type_;
  /**
   * <pre>
   * Type of event to create
   * </pre>
   *
   * <code>.sensory.api.common.UsageEventType type = 5 [(.validate.rules) = { ... }</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override
  public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * Type of event to create
   * </pre>
   *
   * <code>.sensory.api.common.UsageEventType type = 5 [(.validate.rules) = { ... }</code>
   * @return The type.
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.UsageEventType getType() {
    ai.sensorycloud.api.common.UsageEventType result = ai.sensorycloud.api.common.UsageEventType.forNumber(type_);
    return result == null ? ai.sensorycloud.api.common.UsageEventType.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * Type of event to create
   * </pre>
   *
   * <code>.sensory.api.common.UsageEventType type = 5 [(.validate.rules) = { ... }</code>
   * @param value The enum numeric value on the wire for type to set.
   */
  private void setTypeValue(int value) {
      type_ = value;
  }
  /**
   * <pre>
   * Type of event to create
   * </pre>
   *
   * <code>.sensory.api.common.UsageEventType type = 5 [(.validate.rules) = { ... }</code>
   * @param value The type to set.
   */
  private void setType(ai.sensorycloud.api.common.UsageEventType value) {
    type_ = value.getNumber();
    
  }
  /**
   * <pre>
   * Type of event to create
   * </pre>
   *
   * <code>.sensory.api.common.UsageEventType type = 5 [(.validate.rules) = { ... }</code>
   */
  private void clearType() {
    
    type_ = 0;
  }

  public static final int ROUTE_FIELD_NUMBER = 6;
  private java.lang.String route_;
  /**
   * <pre>
   * The specific route (endpoint) that was accessed
   * </pre>
   *
   * <code>string route = 6 [(.validate.rules) = { ... }</code>
   * @return The route.
   */
  @java.lang.Override
  public java.lang.String getRoute() {
    return route_;
  }
  /**
   * <pre>
   * The specific route (endpoint) that was accessed
   * </pre>
   *
   * <code>string route = 6 [(.validate.rules) = { ... }</code>
   * @return The bytes for route.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRouteBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(route_);
  }
  /**
   * <pre>
   * The specific route (endpoint) that was accessed
   * </pre>
   *
   * <code>string route = 6 [(.validate.rules) = { ... }</code>
   * @param value The route to set.
   */
  private void setRoute(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    route_ = value;
  }
  /**
   * <pre>
   * The specific route (endpoint) that was accessed
   * </pre>
   *
   * <code>string route = 6 [(.validate.rules) = { ... }</code>
   */
  private void clearRoute() {
    
    route_ = getDefaultInstance().getRoute();
  }
  /**
   * <pre>
   * The specific route (endpoint) that was accessed
   * </pre>
   *
   * <code>string route = 6 [(.validate.rules) = { ... }</code>
   * @param value The bytes for route to set.
   */
  private void setRouteBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    route_ = value.toStringUtf8();
    
  }

  public static final int TECHNOLOGIES_FIELD_NUMBER = 7;
  private com.google.protobuf.Internal.IntList technologies_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, ai.sensorycloud.api.common.TechnologyType> technologies_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, ai.sensorycloud.api.common.TechnologyType>() {
            @java.lang.Override
            public ai.sensorycloud.api.common.TechnologyType convert(java.lang.Integer from) {
              ai.sensorycloud.api.common.TechnologyType result = ai.sensorycloud.api.common.TechnologyType.forNumber(from);
              return result == null ? ai.sensorycloud.api.common.TechnologyType.UNRECOGNIZED : result;
            }
          };
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   * @return A list containing the technologies.
   */
  @java.lang.Override
  public java.util.List<ai.sensorycloud.api.common.TechnologyType> getTechnologiesList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, ai.sensorycloud.api.common.TechnologyType>(technologies_, technologies_converter_);
  }
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   * @return The count of technologies.
   */
  @java.lang.Override
  public int getTechnologiesCount() {
    return technologies_.size();
  }
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   * @param index The index of the element to return.
   * @return The technologies at the given index.
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.TechnologyType getTechnologies(int index) {
    ai.sensorycloud.api.common.TechnologyType result = ai.sensorycloud.api.common.TechnologyType.forNumber(technologies_.getInt(index));
    return result == null ? ai.sensorycloud.api.common.TechnologyType.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   * @return A list containing the enum numeric values on the wire for technologies.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getTechnologiesValueList() {
    return technologies_;
  }
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of technologies at the given index.
   */
  @java.lang.Override
  public int getTechnologiesValue(int index) {
    return technologies_.getInt(index);
  }
  private int technologiesMemoizedSerializedSize;
  private void ensureTechnologiesIsMutable() {
    com.google.protobuf.Internal.IntList tmp = technologies_;
    if (!tmp.isModifiable()) {
      technologies_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
    }
  }
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   * @param index The index to set the value at.
   * @param value The technologies to set.
   */
  private void setTechnologies(
      int index, ai.sensorycloud.api.common.TechnologyType value) {
    value.getClass();
  ensureTechnologiesIsMutable();
    technologies_.setInt(index, value.getNumber());
  }
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   * @param value The technologies to add.
   */
  private void addTechnologies(ai.sensorycloud.api.common.TechnologyType value) {
    value.getClass();
  ensureTechnologiesIsMutable();
    technologies_.addInt(value.getNumber());
  }
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   * @param values The technologies to add.
   */
  private void addAllTechnologies(
      java.lang.Iterable<? extends ai.sensorycloud.api.common.TechnologyType> values) {
    ensureTechnologiesIsMutable();
    for (ai.sensorycloud.api.common.TechnologyType value : values) {
      technologies_.addInt(value.getNumber());
    }
  }
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   */
  private void clearTechnologies() {
    technologies_ = emptyIntList();
  }
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   * @param value The enum numeric value on the wire for technologies to set.
   */
  private void setTechnologiesValue(
      int index, int value) {
    ensureTechnologiesIsMutable();
    technologies_.setInt(index, value);
  }
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   * @param value The enum numeric value on the wire for technologies to add.
   */
  private void addTechnologiesValue(int value) {
    ensureTechnologiesIsMutable();
    technologies_.addInt(value);
  }
  /**
   * <pre>
   * The technologies that were used
   * </pre>
   *
   * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
   * @param values The enum numeric values on the wire for technologies to add.
   */
  private void addAllTechnologiesValue(
      java.lang.Iterable<java.lang.Integer> values) {
    ensureTechnologiesIsMutable();
    for (int value : values) {
      technologies_.addInt(value);
    }
  }

  public static final int MODELS_FIELD_NUMBER = 8;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> models_;
  /**
   * <pre>
   * The models that were used
   * </pre>
   *
   * <code>repeated string models = 8;</code>
   * @return A list containing the models.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getModelsList() {
    return models_;
  }
  /**
   * <pre>
   * The models that were used
   * </pre>
   *
   * <code>repeated string models = 8;</code>
   * @return The count of models.
   */
  @java.lang.Override
  public int getModelsCount() {
    return models_.size();
  }
  /**
   * <pre>
   * The models that were used
   * </pre>
   *
   * <code>repeated string models = 8;</code>
   * @param index The index of the element to return.
   * @return The models at the given index.
   */
  @java.lang.Override
  public java.lang.String getModels(int index) {
    return models_.get(index);
  }
  /**
   * <pre>
   * The models that were used
   * </pre>
   *
   * <code>repeated string models = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the models at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        models_.get(index));
  }
  private void ensureModelsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        models_;  if (!tmp.isModifiable()) {
      models_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * The models that were used
   * </pre>
   *
   * <code>repeated string models = 8;</code>
   * @param index The index to set the value at.
   * @param value The models to set.
   */
  private void setModels(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureModelsIsMutable();
    models_.set(index, value);
  }
  /**
   * <pre>
   * The models that were used
   * </pre>
   *
   * <code>repeated string models = 8;</code>
   * @param value The models to add.
   */
  private void addModels(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureModelsIsMutable();
    models_.add(value);
  }
  /**
   * <pre>
   * The models that were used
   * </pre>
   *
   * <code>repeated string models = 8;</code>
   * @param values The models to add.
   */
  private void addAllModels(
      java.lang.Iterable<java.lang.String> values) {
    ensureModelsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, models_);
  }
  /**
   * <pre>
   * The models that were used
   * </pre>
   *
   * <code>repeated string models = 8;</code>
   */
  private void clearModels() {
    models_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * The models that were used
   * </pre>
   *
   * <code>repeated string models = 8;</code>
   * @param value The bytes of the models to add.
   */
  private void addModelsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureModelsIsMutable();
    models_.add(value.toStringUtf8());
  }

  public static final int BILLABLEVALUE_FIELD_NUMBER = 9;
  private long billableValue_;
  /**
   * <pre>
   * The value that is billed for this event
   * </pre>
   *
   * <code>int64 billableValue = 9;</code>
   * @return The billableValue.
   */
  @java.lang.Override
  public long getBillableValue() {
    return billableValue_;
  }
  /**
   * <pre>
   * The value that is billed for this event
   * </pre>
   *
   * <code>int64 billableValue = 9;</code>
   * @param value The billableValue to set.
   */
  private void setBillableValue(long value) {
    
    billableValue_ = value;
  }
  /**
   * <pre>
   * The value that is billed for this event
   * </pre>
   *
   * <code>int64 billableValue = 9;</code>
   */
  private void clearBillableValue() {
    
    billableValue_ = 0L;
  }

  public static final int BILLABLEUNITS_FIELD_NUMBER = 10;
  private java.lang.String billableUnits_;
  /**
   * <pre>
   * The units of this billed event
   * </pre>
   *
   * <code>string billableUnits = 10;</code>
   * @return The billableUnits.
   */
  @java.lang.Override
  public java.lang.String getBillableUnits() {
    return billableUnits_;
  }
  /**
   * <pre>
   * The units of this billed event
   * </pre>
   *
   * <code>string billableUnits = 10;</code>
   * @return The bytes for billableUnits.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBillableUnitsBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(billableUnits_);
  }
  /**
   * <pre>
   * The units of this billed event
   * </pre>
   *
   * <code>string billableUnits = 10;</code>
   * @param value The billableUnits to set.
   */
  private void setBillableUnits(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    billableUnits_ = value;
  }
  /**
   * <pre>
   * The units of this billed event
   * </pre>
   *
   * <code>string billableUnits = 10;</code>
   */
  private void clearBillableUnits() {
    
    billableUnits_ = getDefaultInstance().getBillableUnits();
  }
  /**
   * <pre>
   * The units of this billed event
   * </pre>
   *
   * <code>string billableUnits = 10;</code>
   * @param value The bytes for billableUnits to set.
   */
  private void setBillableUnitsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    billableUnits_ = value.toStringUtf8();
    
  }

  public static final int TENANTID_FIELD_NUMBER = 11;
  private java.lang.String tenantId_;
  /**
   * <pre>
   * Optional Tenant ID of the event. Used internally by Sensory multi-tenant servers
   * </pre>
   *
   * <code>string tenantId = 11;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    return tenantId_;
  }
  /**
   * <pre>
   * Optional Tenant ID of the event. Used internally by Sensory multi-tenant servers
   * </pre>
   *
   * <code>string tenantId = 11;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(tenantId_);
  }
  /**
   * <pre>
   * Optional Tenant ID of the event. Used internally by Sensory multi-tenant servers
   * </pre>
   *
   * <code>string tenantId = 11;</code>
   * @param value The tenantId to set.
   */
  private void setTenantId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    tenantId_ = value;
  }
  /**
   * <pre>
   * Optional Tenant ID of the event. Used internally by Sensory multi-tenant servers
   * </pre>
   *
   * <code>string tenantId = 11;</code>
   */
  private void clearTenantId() {
    
    tenantId_ = getDefaultInstance().getTenantId();
  }
  /**
   * <pre>
   * Optional Tenant ID of the event. Used internally by Sensory multi-tenant servers
   * </pre>
   *
   * <code>string tenantId = 11;</code>
   * @param value The bytes for tenantId to set.
   */
  private void setTenantIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    tenantId_ = value.toStringUtf8();
    
  }

  public static final int BILLABLEFUNCTION_FIELD_NUMBER = 12;
  private int billableFunction_;
  /**
   * <pre>
   * Billable function, if applicable
   * </pre>
   *
   * <code>.sensory.api.common.ModelType billableFunction = 12;</code>
   * @return The enum numeric value on the wire for billableFunction.
   */
  @java.lang.Override
  public int getBillableFunctionValue() {
    return billableFunction_;
  }
  /**
   * <pre>
   * Billable function, if applicable
   * </pre>
   *
   * <code>.sensory.api.common.ModelType billableFunction = 12;</code>
   * @return The billableFunction.
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.ModelType getBillableFunction() {
    ai.sensorycloud.api.common.ModelType result = ai.sensorycloud.api.common.ModelType.forNumber(billableFunction_);
    return result == null ? ai.sensorycloud.api.common.ModelType.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * Billable function, if applicable
   * </pre>
   *
   * <code>.sensory.api.common.ModelType billableFunction = 12;</code>
   * @param value The enum numeric value on the wire for billableFunction to set.
   */
  private void setBillableFunctionValue(int value) {
      billableFunction_ = value;
  }
  /**
   * <pre>
   * Billable function, if applicable
   * </pre>
   *
   * <code>.sensory.api.common.ModelType billableFunction = 12;</code>
   * @param value The billableFunction to set.
   */
  private void setBillableFunction(ai.sensorycloud.api.common.ModelType value) {
    billableFunction_ = value.getNumber();
    
  }
  /**
   * <pre>
   * Billable function, if applicable
   * </pre>
   *
   * <code>.sensory.api.common.ModelType billableFunction = 12;</code>
   */
  private void clearBillableFunction() {
    
    billableFunction_ = 0;
  }

  public static final int CREDITS_FIELD_NUMBER = 13;
  private double credits_;
  /**
   * <pre>
   * Credits used by this event
   * </pre>
   *
   * <code>double credits = 13;</code>
   * @return The credits.
   */
  @java.lang.Override
  public double getCredits() {
    return credits_;
  }
  /**
   * <pre>
   * Credits used by this event
   * </pre>
   *
   * <code>double credits = 13;</code>
   * @param value The credits to set.
   */
  private void setCredits(double value) {
    
    credits_ = value;
  }
  /**
   * <pre>
   * Credits used by this event
   * </pre>
   *
   * <code>double credits = 13;</code>
   */
  private void clearCredits() {
    
    credits_ = 0D;
  }

  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.v1.event.UsageEventResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code sensory.api.v1.event.UsageEventResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ai.sensorycloud.api.v1.event.UsageEventResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.v1.event.UsageEventResponse)
      ai.sensorycloud.api.v1.event.UsageEventResponseOrBuilder {
    // Construct using ai.sensorycloud.api.v1.event.UsageEventResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The UTC timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return instance.hasTimestamp();
    }
    /**
     * <pre>
     * The UTC timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestamp() {
      return instance.getTimestamp();
    }
    /**
     * <pre>
     * The UTC timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setTimestamp(value);
      return this;
      }
    /**
     * <pre>
     * The UTC timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setTimestamp(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The UTC timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeTimestamp(value);
      return this;
    }
    /**
     * <pre>
     * The UTC timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder clearTimestamp() {  copyOnWrite();
      instance.clearTimestamp();
      return this;
    }

    /**
     * <pre>
     * The duration of the event in milliseconds
     * </pre>
     *
     * <code>int64 duration = 2 [(.validate.rules) = { ... }</code>
     * @return The duration.
     */
    @java.lang.Override
    public long getDuration() {
      return instance.getDuration();
    }
    /**
     * <pre>
     * The duration of the event in milliseconds
     * </pre>
     *
     * <code>int64 duration = 2 [(.validate.rules) = { ... }</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(long value) {
      copyOnWrite();
      instance.setDuration(value);
      return this;
    }
    /**
     * <pre>
     * The duration of the event in milliseconds
     * </pre>
     *
     * <code>int64 duration = 2 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      copyOnWrite();
      instance.clearDuration();
      return this;
    }

    /**
     * <pre>
     * UUID representing the unique event
     * </pre>
     *
     * <code>string id = 3 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <pre>
     * UUID representing the unique event
     * </pre>
     *
     * <code>string id = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <pre>
     * UUID representing the unique event
     * </pre>
     *
     * <code>string id = 3 [(.validate.rules) = { ... }</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <pre>
     * UUID representing the unique event
     * </pre>
     *
     * <code>string id = 3 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <pre>
     * UUID representing the unique event
     * </pre>
     *
     * <code>string id = 3 [(.validate.rules) = { ... }</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * OAuth ClientID related to the event
     * </pre>
     *
     * <code>string clientId = 4 [(.validate.rules) = { ... }</code>
     * @return The clientId.
     */
    @java.lang.Override
    public java.lang.String getClientId() {
      return instance.getClientId();
    }
    /**
     * <pre>
     * OAuth ClientID related to the event
     * </pre>
     *
     * <code>string clientId = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for clientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      return instance.getClientIdBytes();
    }
    /**
     * <pre>
     * OAuth ClientID related to the event
     * </pre>
     *
     * <code>string clientId = 4 [(.validate.rules) = { ... }</code>
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(
        java.lang.String value) {
      copyOnWrite();
      instance.setClientId(value);
      return this;
    }
    /**
     * <pre>
     * OAuth ClientID related to the event
     * </pre>
     *
     * <code>string clientId = 4 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      copyOnWrite();
      instance.clearClientId();
      return this;
    }
    /**
     * <pre>
     * OAuth ClientID related to the event
     * </pre>
     *
     * <code>string clientId = 4 [(.validate.rules) = { ... }</code>
     * @param value The bytes for clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Type of event to create
     * </pre>
     *
     * <code>.sensory.api.common.UsageEventType type = 5 [(.validate.rules) = { ... }</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return instance.getTypeValue();
    }
    /**
     * <pre>
     * Type of event to create
     * </pre>
     *
     * <code>.sensory.api.common.UsageEventType type = 5 [(.validate.rules) = { ... }</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      copyOnWrite();
      instance.setTypeValue(value);
      return this;
    }
    /**
     * <pre>
     * Type of event to create
     * </pre>
     *
     * <code>.sensory.api.common.UsageEventType type = 5 [(.validate.rules) = { ... }</code>
     * @return The type.
     */
    @java.lang.Override
    public ai.sensorycloud.api.common.UsageEventType getType() {
      return instance.getType();
    }
    /**
     * <pre>
     * Type of event to create
     * </pre>
     *
     * <code>.sensory.api.common.UsageEventType type = 5 [(.validate.rules) = { ... }</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setType(ai.sensorycloud.api.common.UsageEventType value) {
      copyOnWrite();
      instance.setType(value);
      return this;
    }
    /**
     * <pre>
     * Type of event to create
     * </pre>
     *
     * <code>.sensory.api.common.UsageEventType type = 5 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      copyOnWrite();
      instance.clearType();
      return this;
    }

    /**
     * <pre>
     * The specific route (endpoint) that was accessed
     * </pre>
     *
     * <code>string route = 6 [(.validate.rules) = { ... }</code>
     * @return The route.
     */
    @java.lang.Override
    public java.lang.String getRoute() {
      return instance.getRoute();
    }
    /**
     * <pre>
     * The specific route (endpoint) that was accessed
     * </pre>
     *
     * <code>string route = 6 [(.validate.rules) = { ... }</code>
     * @return The bytes for route.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRouteBytes() {
      return instance.getRouteBytes();
    }
    /**
     * <pre>
     * The specific route (endpoint) that was accessed
     * </pre>
     *
     * <code>string route = 6 [(.validate.rules) = { ... }</code>
     * @param value The route to set.
     * @return This builder for chaining.
     */
    public Builder setRoute(
        java.lang.String value) {
      copyOnWrite();
      instance.setRoute(value);
      return this;
    }
    /**
     * <pre>
     * The specific route (endpoint) that was accessed
     * </pre>
     *
     * <code>string route = 6 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearRoute() {
      copyOnWrite();
      instance.clearRoute();
      return this;
    }
    /**
     * <pre>
     * The specific route (endpoint) that was accessed
     * </pre>
     *
     * <code>string route = 6 [(.validate.rules) = { ... }</code>
     * @param value The bytes for route to set.
     * @return This builder for chaining.
     */
    public Builder setRouteBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRouteBytes(value);
      return this;
    }

    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @return A list containing the technologies.
     */
    @java.lang.Override
    public java.util.List<ai.sensorycloud.api.common.TechnologyType> getTechnologiesList() {
      return instance.getTechnologiesList();
    }
    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @return The count of technologies.
     */
    @java.lang.Override
    public int getTechnologiesCount() {
      return instance.getTechnologiesCount();
    }
    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @param index The index of the element to return.
     * @return The technologies at the given index.
     */
    @java.lang.Override
    public ai.sensorycloud.api.common.TechnologyType getTechnologies(int index) {
      return instance.getTechnologies(index);
    }
    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @param index The index to set the value at.
     * @param value The technologies to set.
     * @return This builder for chaining.
     */
    public Builder setTechnologies(
        int index, ai.sensorycloud.api.common.TechnologyType value) {
      copyOnWrite();
      instance.setTechnologies(index, value);
      return this;
    }
    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @param value The technologies to add.
     * @return This builder for chaining.
     */
    public Builder addTechnologies(ai.sensorycloud.api.common.TechnologyType value) {
      copyOnWrite();
      instance.addTechnologies(value);
      return this;
    }
    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @param values The technologies to add.
     * @return This builder for chaining.
     */
    public Builder addAllTechnologies(
        java.lang.Iterable<? extends ai.sensorycloud.api.common.TechnologyType> values) {
      copyOnWrite();
      instance.addAllTechnologies(values);  return this;
    }
    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTechnologies() {
      copyOnWrite();
      instance.clearTechnologies();
      return this;
    }
    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @return A list containing the enum numeric values on the wire for technologies.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getTechnologiesValueList() {
      return java.util.Collections.unmodifiableList(
          instance.getTechnologiesValueList());
    }
    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of technologies at the given index.
     */
    @java.lang.Override
    public int getTechnologiesValue(int index) {
      return instance.getTechnologiesValue(index);
    }
    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for technologies to set.
     * @return This builder for chaining.
     */
    public Builder setTechnologiesValue(
        int index, int value) {
      copyOnWrite();
      instance.setTechnologiesValue(index, value);
      return this;
    }
    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @param value The enum numeric value on the wire for technologies to add.
     * @return This builder for chaining.
     */
    public Builder addTechnologiesValue(int value) {
      instance.addTechnologiesValue(value);
      return this;
    }
    /**
     * <pre>
     * The technologies that were used
     * </pre>
     *
     * <code>repeated .sensory.api.common.TechnologyType technologies = 7;</code>
     * @param values The enum numeric values on the wire for technologies to add.
     * @return This builder for chaining.
     */
    public Builder addAllTechnologiesValue(
        java.lang.Iterable<java.lang.Integer> values) {
      copyOnWrite();
      instance.addAllTechnologiesValue(values);
      return this;
    }

    /**
     * <pre>
     * The models that were used
     * </pre>
     *
     * <code>repeated string models = 8;</code>
     * @return A list containing the models.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getModelsList() {
      return java.util.Collections.unmodifiableList(
          instance.getModelsList());
    }
    /**
     * <pre>
     * The models that were used
     * </pre>
     *
     * <code>repeated string models = 8;</code>
     * @return The count of models.
     */
    @java.lang.Override
    public int getModelsCount() {
      return instance.getModelsCount();
    }
    /**
     * <pre>
     * The models that were used
     * </pre>
     *
     * <code>repeated string models = 8;</code>
     * @param index The index of the element to return.
     * @return The models at the given index.
     */
    @java.lang.Override
    public java.lang.String getModels(int index) {
      return instance.getModels(index);
    }
    /**
     * <pre>
     * The models that were used
     * </pre>
     *
     * <code>repeated string models = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the models at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModelsBytes(int index) {
      return instance.getModelsBytes(index);
    }
    /**
     * <pre>
     * The models that were used
     * </pre>
     *
     * <code>repeated string models = 8;</code>
     * @param index The index to set the value at.
     * @param value The models to set.
     * @return This builder for chaining.
     */
    public Builder setModels(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setModels(index, value);
      return this;
    }
    /**
     * <pre>
     * The models that were used
     * </pre>
     *
     * <code>repeated string models = 8;</code>
     * @param value The models to add.
     * @return This builder for chaining.
     */
    public Builder addModels(
        java.lang.String value) {
      copyOnWrite();
      instance.addModels(value);
      return this;
    }
    /**
     * <pre>
     * The models that were used
     * </pre>
     *
     * <code>repeated string models = 8;</code>
     * @param values The models to add.
     * @return This builder for chaining.
     */
    public Builder addAllModels(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllModels(values);
      return this;
    }
    /**
     * <pre>
     * The models that were used
     * </pre>
     *
     * <code>repeated string models = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearModels() {
      copyOnWrite();
      instance.clearModels();
      return this;
    }
    /**
     * <pre>
     * The models that were used
     * </pre>
     *
     * <code>repeated string models = 8;</code>
     * @param value The bytes of the models to add.
     * @return This builder for chaining.
     */
    public Builder addModelsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addModelsBytes(value);
      return this;
    }

    /**
     * <pre>
     * The value that is billed for this event
     * </pre>
     *
     * <code>int64 billableValue = 9;</code>
     * @return The billableValue.
     */
    @java.lang.Override
    public long getBillableValue() {
      return instance.getBillableValue();
    }
    /**
     * <pre>
     * The value that is billed for this event
     * </pre>
     *
     * <code>int64 billableValue = 9;</code>
     * @param value The billableValue to set.
     * @return This builder for chaining.
     */
    public Builder setBillableValue(long value) {
      copyOnWrite();
      instance.setBillableValue(value);
      return this;
    }
    /**
     * <pre>
     * The value that is billed for this event
     * </pre>
     *
     * <code>int64 billableValue = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearBillableValue() {
      copyOnWrite();
      instance.clearBillableValue();
      return this;
    }

    /**
     * <pre>
     * The units of this billed event
     * </pre>
     *
     * <code>string billableUnits = 10;</code>
     * @return The billableUnits.
     */
    @java.lang.Override
    public java.lang.String getBillableUnits() {
      return instance.getBillableUnits();
    }
    /**
     * <pre>
     * The units of this billed event
     * </pre>
     *
     * <code>string billableUnits = 10;</code>
     * @return The bytes for billableUnits.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBillableUnitsBytes() {
      return instance.getBillableUnitsBytes();
    }
    /**
     * <pre>
     * The units of this billed event
     * </pre>
     *
     * <code>string billableUnits = 10;</code>
     * @param value The billableUnits to set.
     * @return This builder for chaining.
     */
    public Builder setBillableUnits(
        java.lang.String value) {
      copyOnWrite();
      instance.setBillableUnits(value);
      return this;
    }
    /**
     * <pre>
     * The units of this billed event
     * </pre>
     *
     * <code>string billableUnits = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBillableUnits() {
      copyOnWrite();
      instance.clearBillableUnits();
      return this;
    }
    /**
     * <pre>
     * The units of this billed event
     * </pre>
     *
     * <code>string billableUnits = 10;</code>
     * @param value The bytes for billableUnits to set.
     * @return This builder for chaining.
     */
    public Builder setBillableUnitsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBillableUnitsBytes(value);
      return this;
    }

    /**
     * <pre>
     * Optional Tenant ID of the event. Used internally by Sensory multi-tenant servers
     * </pre>
     *
     * <code>string tenantId = 11;</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public java.lang.String getTenantId() {
      return instance.getTenantId();
    }
    /**
     * <pre>
     * Optional Tenant ID of the event. Used internally by Sensory multi-tenant servers
     * </pre>
     *
     * <code>string tenantId = 11;</code>
     * @return The bytes for tenantId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      return instance.getTenantIdBytes();
    }
    /**
     * <pre>
     * Optional Tenant ID of the event. Used internally by Sensory multi-tenant servers
     * </pre>
     *
     * <code>string tenantId = 11;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTenantId(value);
      return this;
    }
    /**
     * <pre>
     * Optional Tenant ID of the event. Used internally by Sensory multi-tenant servers
     * </pre>
     *
     * <code>string tenantId = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      copyOnWrite();
      instance.clearTenantId();
      return this;
    }
    /**
     * <pre>
     * Optional Tenant ID of the event. Used internally by Sensory multi-tenant servers
     * </pre>
     *
     * <code>string tenantId = 11;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTenantIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Billable function, if applicable
     * </pre>
     *
     * <code>.sensory.api.common.ModelType billableFunction = 12;</code>
     * @return The enum numeric value on the wire for billableFunction.
     */
    @java.lang.Override
    public int getBillableFunctionValue() {
      return instance.getBillableFunctionValue();
    }
    /**
     * <pre>
     * Billable function, if applicable
     * </pre>
     *
     * <code>.sensory.api.common.ModelType billableFunction = 12;</code>
     * @param value The billableFunction to set.
     * @return This builder for chaining.
     */
    public Builder setBillableFunctionValue(int value) {
      copyOnWrite();
      instance.setBillableFunctionValue(value);
      return this;
    }
    /**
     * <pre>
     * Billable function, if applicable
     * </pre>
     *
     * <code>.sensory.api.common.ModelType billableFunction = 12;</code>
     * @return The billableFunction.
     */
    @java.lang.Override
    public ai.sensorycloud.api.common.ModelType getBillableFunction() {
      return instance.getBillableFunction();
    }
    /**
     * <pre>
     * Billable function, if applicable
     * </pre>
     *
     * <code>.sensory.api.common.ModelType billableFunction = 12;</code>
     * @param value The enum numeric value on the wire for billableFunction to set.
     * @return This builder for chaining.
     */
    public Builder setBillableFunction(ai.sensorycloud.api.common.ModelType value) {
      copyOnWrite();
      instance.setBillableFunction(value);
      return this;
    }
    /**
     * <pre>
     * Billable function, if applicable
     * </pre>
     *
     * <code>.sensory.api.common.ModelType billableFunction = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearBillableFunction() {
      copyOnWrite();
      instance.clearBillableFunction();
      return this;
    }

    /**
     * <pre>
     * Credits used by this event
     * </pre>
     *
     * <code>double credits = 13;</code>
     * @return The credits.
     */
    @java.lang.Override
    public double getCredits() {
      return instance.getCredits();
    }
    /**
     * <pre>
     * Credits used by this event
     * </pre>
     *
     * <code>double credits = 13;</code>
     * @param value The credits to set.
     * @return This builder for chaining.
     */
    public Builder setCredits(double value) {
      copyOnWrite();
      instance.setCredits(value);
      return this;
    }
    /**
     * <pre>
     * Credits used by this event
     * </pre>
     *
     * <code>double credits = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearCredits() {
      copyOnWrite();
      instance.clearCredits();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sensory.api.v1.event.UsageEventResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ai.sensorycloud.api.v1.event.UsageEventResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "timestamp_",
            "duration_",
            "id_",
            "clientId_",
            "type_",
            "route_",
            "technologies_",
            "models_",
            "billableValue_",
            "billableUnits_",
            "tenantId_",
            "billableFunction_",
            "credits_",
          };
          java.lang.String info =
              "\u0000\r\u0000\u0000\u0001\r\r\u0000\u0002\u0000\u0001\t\u0002\u0002\u0003\u0208" +
              "\u0004\u0208\u0005\f\u0006\u0208\u0007,\b\u021a\t\u0002\n\u0208\u000b\u0208\f\f\r" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ai.sensorycloud.api.v1.event.UsageEventResponse> parser = PARSER;
        if (parser == null) {
          synchronized (ai.sensorycloud.api.v1.event.UsageEventResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ai.sensorycloud.api.v1.event.UsageEventResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sensory.api.v1.event.UsageEventResponse)
  private static final ai.sensorycloud.api.v1.event.UsageEventResponse DEFAULT_INSTANCE;
  static {
    UsageEventResponse defaultInstance = new UsageEventResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UsageEventResponse.class, defaultInstance);
  }

  public static ai.sensorycloud.api.v1.event.UsageEventResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UsageEventResponse> PARSER;

  public static com.google.protobuf.Parser<UsageEventResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

