// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/file/file.proto

package ai.sensorycloud.api.v1.file;

/**
 * <pre>
 * A request to obtain a catalog of all files
 * </pre>
 *
 * Protobuf type {@code sensory.api.v1.file.FileCatalogRequest}
 */
public  final class FileCatalogRequest extends
    com.google.protobuf.GeneratedMessageLite<
        FileCatalogRequest, FileCatalogRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:sensory.api.v1.file.FileCatalogRequest)
    FileCatalogRequestOrBuilder {
  private FileCatalogRequest() {
    categories_ = emptyProtobufList();
  }
  public static final int CATEGORIES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<ai.sensorycloud.api.v1.file.VersionedFileCategory> categories_;
  /**
   * <pre>
   * A map of file category versions
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public java.util.List<ai.sensorycloud.api.v1.file.VersionedFileCategory> getCategoriesList() {
    return categories_;
  }
  /**
   * <pre>
   * A map of file category versions
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
   */
  public java.util.List<? extends ai.sensorycloud.api.v1.file.VersionedFileCategoryOrBuilder> 
      getCategoriesOrBuilderList() {
    return categories_;
  }
  /**
   * <pre>
   * A map of file category versions
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public int getCategoriesCount() {
    return categories_.size();
  }
  /**
   * <pre>
   * A map of file category versions
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public ai.sensorycloud.api.v1.file.VersionedFileCategory getCategories(int index) {
    return categories_.get(index);
  }
  /**
   * <pre>
   * A map of file category versions
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
   */
  public ai.sensorycloud.api.v1.file.VersionedFileCategoryOrBuilder getCategoriesOrBuilder(
      int index) {
    return categories_.get(index);
  }
  private void ensureCategoriesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<ai.sensorycloud.api.v1.file.VersionedFileCategory> tmp = categories_;
    if (!tmp.isModifiable()) {
      categories_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * A map of file category versions
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
   */
  private void setCategories(
      int index, ai.sensorycloud.api.v1.file.VersionedFileCategory value) {
    value.getClass();
  ensureCategoriesIsMutable();
    categories_.set(index, value);
  }
  /**
   * <pre>
   * A map of file category versions
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
   */
  private void addCategories(ai.sensorycloud.api.v1.file.VersionedFileCategory value) {
    value.getClass();
  ensureCategoriesIsMutable();
    categories_.add(value);
  }
  /**
   * <pre>
   * A map of file category versions
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
   */
  private void addCategories(
      int index, ai.sensorycloud.api.v1.file.VersionedFileCategory value) {
    value.getClass();
  ensureCategoriesIsMutable();
    categories_.add(index, value);
  }
  /**
   * <pre>
   * A map of file category versions
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
   */
  private void addAllCategories(
      java.lang.Iterable<? extends ai.sensorycloud.api.v1.file.VersionedFileCategory> values) {
    ensureCategoriesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, categories_);
  }
  /**
   * <pre>
   * A map of file category versions
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
   */
  private void clearCategories() {
    categories_ = emptyProtobufList();
  }
  /**
   * <pre>
   * A map of file category versions
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
   */
  private void removeCategories(int index) {
    ensureCategoriesIsMutable();
    categories_.remove(index);
  }

  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.file.FileCatalogRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.v1.file.FileCatalogRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A request to obtain a catalog of all files
   * </pre>
   *
   * Protobuf type {@code sensory.api.v1.file.FileCatalogRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ai.sensorycloud.api.v1.file.FileCatalogRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.v1.file.FileCatalogRequest)
      ai.sensorycloud.api.v1.file.FileCatalogRequestOrBuilder {
    // Construct using ai.sensorycloud.api.v1.file.FileCatalogRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public java.util.List<ai.sensorycloud.api.v1.file.VersionedFileCategory> getCategoriesList() {
      return java.util.Collections.unmodifiableList(
          instance.getCategoriesList());
    }
    /**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public int getCategoriesCount() {
      return instance.getCategoriesCount();
    }/**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public ai.sensorycloud.api.v1.file.VersionedFileCategory getCategories(int index) {
      return instance.getCategories(index);
    }
    /**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder setCategories(
        int index, ai.sensorycloud.api.v1.file.VersionedFileCategory value) {
      copyOnWrite();
      instance.setCategories(index, value);
      return this;
    }
    /**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder setCategories(
        int index, ai.sensorycloud.api.v1.file.VersionedFileCategory.Builder builderForValue) {
      copyOnWrite();
      instance.setCategories(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder addCategories(ai.sensorycloud.api.v1.file.VersionedFileCategory value) {
      copyOnWrite();
      instance.addCategories(value);
      return this;
    }
    /**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder addCategories(
        int index, ai.sensorycloud.api.v1.file.VersionedFileCategory value) {
      copyOnWrite();
      instance.addCategories(index, value);
      return this;
    }
    /**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder addCategories(
        ai.sensorycloud.api.v1.file.VersionedFileCategory.Builder builderForValue) {
      copyOnWrite();
      instance.addCategories(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder addCategories(
        int index, ai.sensorycloud.api.v1.file.VersionedFileCategory.Builder builderForValue) {
      copyOnWrite();
      instance.addCategories(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder addAllCategories(
        java.lang.Iterable<? extends ai.sensorycloud.api.v1.file.VersionedFileCategory> values) {
      copyOnWrite();
      instance.addAllCategories(values);
      return this;
    }
    /**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder clearCategories() {
      copyOnWrite();
      instance.clearCategories();
      return this;
    }
    /**
     * <pre>
     * A map of file category versions
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.VersionedFileCategory categories = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder removeCategories(int index) {
      copyOnWrite();
      instance.removeCategories(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sensory.api.v1.file.FileCatalogRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ai.sensorycloud.api.v1.file.FileCatalogRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "categories_",
            ai.sensorycloud.api.v1.file.VersionedFileCategory.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ai.sensorycloud.api.v1.file.FileCatalogRequest> parser = PARSER;
        if (parser == null) {
          synchronized (ai.sensorycloud.api.v1.file.FileCatalogRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ai.sensorycloud.api.v1.file.FileCatalogRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sensory.api.v1.file.FileCatalogRequest)
  private static final ai.sensorycloud.api.v1.file.FileCatalogRequest DEFAULT_INSTANCE;
  static {
    FileCatalogRequest defaultInstance = new FileCatalogRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FileCatalogRequest.class, defaultInstance);
  }

  public static ai.sensorycloud.api.v1.file.FileCatalogRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FileCatalogRequest> PARSER;

  public static com.google.protobuf.Parser<FileCatalogRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

