// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oauth/oauth.proto

package ai.sensorycloud.api.oauth;

/**
 * <pre>
 * Response to a public key request. Holds a byte array representing the public key.
 * </pre>
 *
 * Protobuf type {@code sensory.api.oauth.PublicKeyResponse}
 */
public  final class PublicKeyResponse extends
    com.google.protobuf.GeneratedMessageLite<
        PublicKeyResponse, PublicKeyResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:sensory.api.oauth.PublicKeyResponse)
    PublicKeyResponseOrBuilder {
  private PublicKeyResponse() {
    publicKey_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int PUBLICKEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString publicKey_;
  /**
   * <pre>
   * The public key as bytes
   * </pre>
   *
   * <code>bytes publicKey = 1;</code>
   * @return The publicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPublicKey() {
    return publicKey_;
  }
  /**
   * <pre>
   * The public key as bytes
   * </pre>
   *
   * <code>bytes publicKey = 1;</code>
   * @param value The publicKey to set.
   */
  private void setPublicKey(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    publicKey_ = value;
  }
  /**
   * <pre>
   * The public key as bytes
   * </pre>
   *
   * <code>bytes publicKey = 1;</code>
   */
  private void clearPublicKey() {

    publicKey_ = getDefaultInstance().getPublicKey();
  }

  public static final int KEYTYPE_FIELD_NUMBER = 2;
  private int keyType_;
  /**
   * <pre>
   * The key type
   * </pre>
   *
   * <code>.sensory.api.common.KeyType keyType = 2;</code>
   * @return The enum numeric value on the wire for keyType.
   */
  @java.lang.Override
  public int getKeyTypeValue() {
    return keyType_;
  }
  /**
   * <pre>
   * The key type
   * </pre>
   *
   * <code>.sensory.api.common.KeyType keyType = 2;</code>
   * @return The keyType.
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.KeyType getKeyType() {
    ai.sensorycloud.api.common.KeyType result = ai.sensorycloud.api.common.KeyType.forNumber(keyType_);
    return result == null ? ai.sensorycloud.api.common.KeyType.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * The key type
   * </pre>
   *
   * <code>.sensory.api.common.KeyType keyType = 2;</code>
   * @param value The enum numeric value on the wire for keyType to set.
   */
  private void setKeyTypeValue(int value) {
      keyType_ = value;
  }
  /**
   * <pre>
   * The key type
   * </pre>
   *
   * <code>.sensory.api.common.KeyType keyType = 2;</code>
   * @param value The keyType to set.
   */
  private void setKeyType(ai.sensorycloud.api.common.KeyType value) {
    keyType_ = value.getNumber();

  }
  /**
   * <pre>
   * The key type
   * </pre>
   *
   * <code>.sensory.api.common.KeyType keyType = 2;</code>
   */
  private void clearKeyType() {

    keyType_ = 0;
  }

  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.oauth.PublicKeyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.oauth.PublicKeyResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Response to a public key request. Holds a byte array representing the public key.
   * </pre>
   *
   * Protobuf type {@code sensory.api.oauth.PublicKeyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ai.sensorycloud.api.oauth.PublicKeyResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.oauth.PublicKeyResponse)
      ai.sensorycloud.api.oauth.PublicKeyResponseOrBuilder {
    // Construct using ai.sensorycloud.api.oauth.PublicKeyResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The public key as bytes
     * </pre>
     *
     * <code>bytes publicKey = 1;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKey() {
      return instance.getPublicKey();
    }
    /**
     * <pre>
     * The public key as bytes
     * </pre>
     *
     * <code>bytes publicKey = 1;</code>
     * @param value The publicKey to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKey(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPublicKey(value);
      return this;
    }
    /**
     * <pre>
     * The public key as bytes
     * </pre>
     *
     * <code>bytes publicKey = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicKey() {
      copyOnWrite();
      instance.clearPublicKey();
      return this;
    }

    /**
     * <pre>
     * The key type
     * </pre>
     *
     * <code>.sensory.api.common.KeyType keyType = 2;</code>
     * @return The enum numeric value on the wire for keyType.
     */
    @java.lang.Override
    public int getKeyTypeValue() {
      return instance.getKeyTypeValue();
    }
    /**
     * <pre>
     * The key type
     * </pre>
     *
     * <code>.sensory.api.common.KeyType keyType = 2;</code>
     * @param value The keyType to set.
     * @return This builder for chaining.
     */
    public Builder setKeyTypeValue(int value) {
      copyOnWrite();
      instance.setKeyTypeValue(value);
      return this;
    }
    /**
     * <pre>
     * The key type
     * </pre>
     *
     * <code>.sensory.api.common.KeyType keyType = 2;</code>
     * @return The keyType.
     */
    @java.lang.Override
    public ai.sensorycloud.api.common.KeyType getKeyType() {
      return instance.getKeyType();
    }
    /**
     * <pre>
     * The key type
     * </pre>
     *
     * <code>.sensory.api.common.KeyType keyType = 2;</code>
     * @param value The enum numeric value on the wire for keyType to set.
     * @return This builder for chaining.
     */
    public Builder setKeyType(ai.sensorycloud.api.common.KeyType value) {
      copyOnWrite();
      instance.setKeyType(value);
      return this;
    }
    /**
     * <pre>
     * The key type
     * </pre>
     *
     * <code>.sensory.api.common.KeyType keyType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyType() {
      copyOnWrite();
      instance.clearKeyType();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sensory.api.oauth.PublicKeyResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ai.sensorycloud.api.oauth.PublicKeyResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "publicKey_",
            "keyType_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\n\u0002\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ai.sensorycloud.api.oauth.PublicKeyResponse> parser = PARSER;
        if (parser == null) {
          synchronized (ai.sensorycloud.api.oauth.PublicKeyResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ai.sensorycloud.api.oauth.PublicKeyResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sensory.api.oauth.PublicKeyResponse)
  private static final ai.sensorycloud.api.oauth.PublicKeyResponse DEFAULT_INSTANCE;
  static {
    PublicKeyResponse defaultInstance = new PublicKeyResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PublicKeyResponse.class, defaultInstance);
  }

  public static ai.sensorycloud.api.oauth.PublicKeyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PublicKeyResponse> PARSER;

  public static com.google.protobuf.Parser<PublicKeyResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

