// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/audio/audio.proto

package ai.sensorycloud.api.v1.audio;

/**
 * <pre>
 * The top-level message sent by the client for the `Authenticate` method.
 * Multiple `AuthenticateRequest` messages are sent in a stream. The first message
 * must contain a `config` message and must not contain `audioContent`.
 * All subsequent messages must contain `audioContent` and
 * must not contain a `config` message.
 * </pre>
 *
 * Protobuf type {@code sensory.api.v1.audio.AuthenticateRequest}
 */
public  final class AuthenticateRequest extends
    com.google.protobuf.GeneratedMessageLite<
        AuthenticateRequest, AuthenticateRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:sensory.api.v1.audio.AuthenticateRequest)
    AuthenticateRequestOrBuilder {
  private AuthenticateRequest() {
  }
  private int streamingRequestCase_ = 0;
  private java.lang.Object streamingRequest_;
  public enum StreamingRequestCase {
    CONFIG(1),
    AUDIOCONTENT(2),
    STREAMINGREQUEST_NOT_SET(0);
    private final int value;
    private StreamingRequestCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StreamingRequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static StreamingRequestCase forNumber(int value) {
      switch (value) {
        case 1: return CONFIG;
        case 2: return AUDIOCONTENT;
        case 0: return STREAMINGREQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public StreamingRequestCase
  getStreamingRequestCase() {
    return StreamingRequestCase.forNumber(
        streamingRequestCase_);
  }

  private void clearStreamingRequest() {
    streamingRequestCase_ = 0;
    streamingRequest_ = null;
  }

  public static final int CONFIG_FIELD_NUMBER = 1;
  /**
   * <pre>
   * Provides information that specifies how to process the
   * request. The first `AuthenticateRequest` message must contain a
   * `config`  message.
   * </pre>
   *
   * <code>.sensory.api.v1.audio.AuthenticateConfig config = 1;</code>
   */
  @java.lang.Override
  public boolean hasConfig() {
    return streamingRequestCase_ == 1;
  }
  /**
   * <pre>
   * Provides information that specifies how to process the
   * request. The first `AuthenticateRequest` message must contain a
   * `config`  message.
   * </pre>
   *
   * <code>.sensory.api.v1.audio.AuthenticateConfig config = 1;</code>
   */
  @java.lang.Override
  public ai.sensorycloud.api.v1.audio.AuthenticateConfig getConfig() {
    if (streamingRequestCase_ == 1) {
       return (ai.sensorycloud.api.v1.audio.AuthenticateConfig) streamingRequest_;
    }
    return ai.sensorycloud.api.v1.audio.AuthenticateConfig.getDefaultInstance();
  }
  /**
   * <pre>
   * Provides information that specifies how to process the
   * request. The first `AuthenticateRequest` message must contain a
   * `config`  message.
   * </pre>
   *
   * <code>.sensory.api.v1.audio.AuthenticateConfig config = 1;</code>
   */
  private void setConfig(ai.sensorycloud.api.v1.audio.AuthenticateConfig value) {
    value.getClass();
  streamingRequest_ = value;
    streamingRequestCase_ = 1;
  }
  /**
   * <pre>
   * Provides information that specifies how to process the
   * request. The first `AuthenticateRequest` message must contain a
   * `config`  message.
   * </pre>
   *
   * <code>.sensory.api.v1.audio.AuthenticateConfig config = 1;</code>
   */
  private void mergeConfig(ai.sensorycloud.api.v1.audio.AuthenticateConfig value) {
    value.getClass();
  if (streamingRequestCase_ == 1 &&
        streamingRequest_ != ai.sensorycloud.api.v1.audio.AuthenticateConfig.getDefaultInstance()) {
      streamingRequest_ = ai.sensorycloud.api.v1.audio.AuthenticateConfig.newBuilder((ai.sensorycloud.api.v1.audio.AuthenticateConfig) streamingRequest_)
          .mergeFrom(value).buildPartial();
    } else {
      streamingRequest_ = value;
    }
    streamingRequestCase_ = 1;
  }
  /**
   * <pre>
   * Provides information that specifies how to process the
   * request. The first `AuthenticateRequest` message must contain a
   * `config`  message.
   * </pre>
   *
   * <code>.sensory.api.v1.audio.AuthenticateConfig config = 1;</code>
   */
  private void clearConfig() {
    if (streamingRequestCase_ == 1) {
      streamingRequestCase_ = 0;
      streamingRequest_ = null;
    }
  }

  public static final int AUDIOCONTENT_FIELD_NUMBER = 2;
  /**
   * <pre>
   * The audio data to be recognized. Sequential chunks of audio data are sent
   * in sequential `AuthenticateRequest` messages. The first
   * `AuthenticateRequest` message must not contain `audioContent` data
   * and all subsequent `AuthenticateRequest` messages must contain
   * `audioContent` data. The audio bytes must be encoded as specified in
   * `AuthenticateConfig`.
   * </pre>
   *
   * <code>bytes audioContent = 2;</code>
   * @return Whether the audioContent field is set.
   */
  @java.lang.Override
  public boolean hasAudioContent() {
    return streamingRequestCase_ == 2;
  }
  /**
   * <pre>
   * The audio data to be recognized. Sequential chunks of audio data are sent
   * in sequential `AuthenticateRequest` messages. The first
   * `AuthenticateRequest` message must not contain `audioContent` data
   * and all subsequent `AuthenticateRequest` messages must contain
   * `audioContent` data. The audio bytes must be encoded as specified in
   * `AuthenticateConfig`.
   * </pre>
   *
   * <code>bytes audioContent = 2;</code>
   * @return The audioContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAudioContent() {
    if (streamingRequestCase_ == 2) {
      return (com.google.protobuf.ByteString) streamingRequest_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }
  /**
   * <pre>
   * The audio data to be recognized. Sequential chunks of audio data are sent
   * in sequential `AuthenticateRequest` messages. The first
   * `AuthenticateRequest` message must not contain `audioContent` data
   * and all subsequent `AuthenticateRequest` messages must contain
   * `audioContent` data. The audio bytes must be encoded as specified in
   * `AuthenticateConfig`.
   * </pre>
   *
   * <code>bytes audioContent = 2;</code>
   * @param value The audioContent to set.
   */
  private void setAudioContent(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  streamingRequestCase_ = 2;
    streamingRequest_ = value;
  }
  /**
   * <pre>
   * The audio data to be recognized. Sequential chunks of audio data are sent
   * in sequential `AuthenticateRequest` messages. The first
   * `AuthenticateRequest` message must not contain `audioContent` data
   * and all subsequent `AuthenticateRequest` messages must contain
   * `audioContent` data. The audio bytes must be encoded as specified in
   * `AuthenticateConfig`.
   * </pre>
   *
   * <code>bytes audioContent = 2;</code>
   */
  private void clearAudioContent() {
    if (streamingRequestCase_ == 2) {
      streamingRequestCase_ = 0;
      streamingRequest_ = null;
    }
  }

  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.v1.audio.AuthenticateRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The top-level message sent by the client for the `Authenticate` method.
   * Multiple `AuthenticateRequest` messages are sent in a stream. The first message
   * must contain a `config` message and must not contain `audioContent`.
   * All subsequent messages must contain `audioContent` and
   * must not contain a `config` message.
   * </pre>
   *
   * Protobuf type {@code sensory.api.v1.audio.AuthenticateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ai.sensorycloud.api.v1.audio.AuthenticateRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.v1.audio.AuthenticateRequest)
      ai.sensorycloud.api.v1.audio.AuthenticateRequestOrBuilder {
    // Construct using ai.sensorycloud.api.v1.audio.AuthenticateRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public StreamingRequestCase
        getStreamingRequestCase() {
      return instance.getStreamingRequestCase();
    }

    public Builder clearStreamingRequest() {
      copyOnWrite();
      instance.clearStreamingRequest();
      return this;
    }


    /**
     * <pre>
     * Provides information that specifies how to process the
     * request. The first `AuthenticateRequest` message must contain a
     * `config`  message.
     * </pre>
     *
     * <code>.sensory.api.v1.audio.AuthenticateConfig config = 1;</code>
     */
    @java.lang.Override
    public boolean hasConfig() {
      return instance.hasConfig();
    }
    /**
     * <pre>
     * Provides information that specifies how to process the
     * request. The first `AuthenticateRequest` message must contain a
     * `config`  message.
     * </pre>
     *
     * <code>.sensory.api.v1.audio.AuthenticateConfig config = 1;</code>
     */
    @java.lang.Override
    public ai.sensorycloud.api.v1.audio.AuthenticateConfig getConfig() {
      return instance.getConfig();
    }
    /**
     * <pre>
     * Provides information that specifies how to process the
     * request. The first `AuthenticateRequest` message must contain a
     * `config`  message.
     * </pre>
     *
     * <code>.sensory.api.v1.audio.AuthenticateConfig config = 1;</code>
     */
    public Builder setConfig(ai.sensorycloud.api.v1.audio.AuthenticateConfig value) {
      copyOnWrite();
      instance.setConfig(value);
      return this;
    }
    /**
     * <pre>
     * Provides information that specifies how to process the
     * request. The first `AuthenticateRequest` message must contain a
     * `config`  message.
     * </pre>
     *
     * <code>.sensory.api.v1.audio.AuthenticateConfig config = 1;</code>
     */
    public Builder setConfig(
        ai.sensorycloud.api.v1.audio.AuthenticateConfig.Builder builderForValue) {
      copyOnWrite();
      instance.setConfig(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Provides information that specifies how to process the
     * request. The first `AuthenticateRequest` message must contain a
     * `config`  message.
     * </pre>
     *
     * <code>.sensory.api.v1.audio.AuthenticateConfig config = 1;</code>
     */
    public Builder mergeConfig(ai.sensorycloud.api.v1.audio.AuthenticateConfig value) {
      copyOnWrite();
      instance.mergeConfig(value);
      return this;
    }
    /**
     * <pre>
     * Provides information that specifies how to process the
     * request. The first `AuthenticateRequest` message must contain a
     * `config`  message.
     * </pre>
     *
     * <code>.sensory.api.v1.audio.AuthenticateConfig config = 1;</code>
     */
    public Builder clearConfig() {
      copyOnWrite();
      instance.clearConfig();
      return this;
    }

    /**
     * <pre>
     * The audio data to be recognized. Sequential chunks of audio data are sent
     * in sequential `AuthenticateRequest` messages. The first
     * `AuthenticateRequest` message must not contain `audioContent` data
     * and all subsequent `AuthenticateRequest` messages must contain
     * `audioContent` data. The audio bytes must be encoded as specified in
     * `AuthenticateConfig`.
     * </pre>
     *
     * <code>bytes audioContent = 2;</code>
     * @return Whether the audioContent field is set.
     */
    @java.lang.Override
    public boolean hasAudioContent() {
      return instance.hasAudioContent();
    }
    /**
     * <pre>
     * The audio data to be recognized. Sequential chunks of audio data are sent
     * in sequential `AuthenticateRequest` messages. The first
     * `AuthenticateRequest` message must not contain `audioContent` data
     * and all subsequent `AuthenticateRequest` messages must contain
     * `audioContent` data. The audio bytes must be encoded as specified in
     * `AuthenticateConfig`.
     * </pre>
     *
     * <code>bytes audioContent = 2;</code>
     * @return The audioContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAudioContent() {
      return instance.getAudioContent();
    }
    /**
     * <pre>
     * The audio data to be recognized. Sequential chunks of audio data are sent
     * in sequential `AuthenticateRequest` messages. The first
     * `AuthenticateRequest` message must not contain `audioContent` data
     * and all subsequent `AuthenticateRequest` messages must contain
     * `audioContent` data. The audio bytes must be encoded as specified in
     * `AuthenticateConfig`.
     * </pre>
     *
     * <code>bytes audioContent = 2;</code>
     * @param value The audioContent to set.
     * @return This builder for chaining.
     */
    public Builder setAudioContent(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAudioContent(value);
      return this;
    }
    /**
     * <pre>
     * The audio data to be recognized. Sequential chunks of audio data are sent
     * in sequential `AuthenticateRequest` messages. The first
     * `AuthenticateRequest` message must not contain `audioContent` data
     * and all subsequent `AuthenticateRequest` messages must contain
     * `audioContent` data. The audio bytes must be encoded as specified in
     * `AuthenticateConfig`.
     * </pre>
     *
     * <code>bytes audioContent = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudioContent() {
      copyOnWrite();
      instance.clearAudioContent();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sensory.api.v1.audio.AuthenticateRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ai.sensorycloud.api.v1.audio.AuthenticateRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "streamingRequest_",
            "streamingRequestCase_",
            ai.sensorycloud.api.v1.audio.AuthenticateConfig.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001<\u0000\u0002=" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ai.sensorycloud.api.v1.audio.AuthenticateRequest> parser = PARSER;
        if (parser == null) {
          synchronized (ai.sensorycloud.api.v1.audio.AuthenticateRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ai.sensorycloud.api.v1.audio.AuthenticateRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sensory.api.v1.audio.AuthenticateRequest)
  private static final ai.sensorycloud.api.v1.audio.AuthenticateRequest DEFAULT_INSTANCE;
  static {
    AuthenticateRequest defaultInstance = new AuthenticateRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AuthenticateRequest.class, defaultInstance);
  }

  public static ai.sensorycloud.api.v1.audio.AuthenticateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AuthenticateRequest> PARSER;

  public static com.google.protobuf.Parser<AuthenticateRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

