// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/audio/audio.proto

package ai.sensorycloud.api.v1.audio;

/**
 * Protobuf enum {@code sensory.api.v1.audio.WordState}
 */
public enum WordState
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <pre>
   *Default state is PENDING which indicates that the speech system may decide to change the word in the future given additional audio data
   * </pre>
   *
   * <code>WORDSTATE_PENDING = 0;</code>
   */
  WORDSTATE_PENDING(0),
  /**
   * <pre>
   *Final state FINAL indicates that the word has moved out of the active logit buffer and can no longer be updated given additional information
   * </pre>
   *
   * <code>WORDSTATE_FINAL = 1;</code>
   */
  WORDSTATE_FINAL(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *Default state is PENDING which indicates that the speech system may decide to change the word in the future given additional audio data
   * </pre>
   *
   * <code>WORDSTATE_PENDING = 0;</code>
   */
  public static final int WORDSTATE_PENDING_VALUE = 0;
  /**
   * <pre>
   *Final state FINAL indicates that the word has moved out of the active logit buffer and can no longer be updated given additional information
   * </pre>
   *
   * <code>WORDSTATE_FINAL = 1;</code>
   */
  public static final int WORDSTATE_FINAL_VALUE = 1;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static WordState valueOf(int value) {
    return forNumber(value);
  }

  public static WordState forNumber(int value) {
    switch (value) {
      case 0: return WORDSTATE_PENDING;
      case 1: return WORDSTATE_FINAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<WordState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      WordState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<WordState>() {
          @java.lang.Override
          public WordState findValueByNumber(int number) {
            return WordState.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return WordStateVerifier.INSTANCE;
  }

  private static final class WordStateVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new WordStateVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return WordState.forNumber(number) != null;
          }
        };

  private final int value;

  private WordState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:sensory.api.v1.audio.WordState)
}

