// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/common.proto

package io.sensory.api.common;

/**
 * <pre>
 * A summary of system statistics
 * </pre>
 *
 * Protobuf type {@code sensory.api.common.SystemSummary}
 */
public  final class SystemSummary extends
    com.google.protobuf.GeneratedMessageLite<
        SystemSummary, SystemSummary.Builder> implements
    // @@protoc_insertion_point(message_implements:sensory.api.common.SystemSummary)
    SystemSummaryOrBuilder {
  private SystemSummary() {
  }
  public static final int CPU_FIELD_NUMBER = 1;
  private io.sensory.api.common.CpuSummary cpu_;
  /**
   * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public boolean hasCpu() {
    return cpu_ != null;
  }
  /**
   * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public io.sensory.api.common.CpuSummary getCpu() {
    return cpu_ == null ? io.sensory.api.common.CpuSummary.getDefaultInstance() : cpu_;
  }
  /**
   * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
   */
  private void setCpu(io.sensory.api.common.CpuSummary value) {
    value.getClass();
  cpu_ = value;
    
    }
  /**
   * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeCpu(io.sensory.api.common.CpuSummary value) {
    value.getClass();
  if (cpu_ != null &&
        cpu_ != io.sensory.api.common.CpuSummary.getDefaultInstance()) {
      cpu_ =
        io.sensory.api.common.CpuSummary.newBuilder(cpu_).mergeFrom(value).buildPartial();
    } else {
      cpu_ = value;
    }
    
  }
  /**
   * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
   */
  private void clearCpu() {  cpu_ = null;
    
  }

  public static final int MEMORY_FIELD_NUMBER = 2;
  private io.sensory.api.common.MemorySummary memory_;
  /**
   * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public boolean hasMemory() {
    return memory_ != null;
  }
  /**
   * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public io.sensory.api.common.MemorySummary getMemory() {
    return memory_ == null ? io.sensory.api.common.MemorySummary.getDefaultInstance() : memory_;
  }
  /**
   * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
   */
  private void setMemory(io.sensory.api.common.MemorySummary value) {
    value.getClass();
  memory_ = value;
    
    }
  /**
   * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeMemory(io.sensory.api.common.MemorySummary value) {
    value.getClass();
  if (memory_ != null &&
        memory_ != io.sensory.api.common.MemorySummary.getDefaultInstance()) {
      memory_ =
        io.sensory.api.common.MemorySummary.newBuilder(memory_).mergeFrom(value).buildPartial();
    } else {
      memory_ = value;
    }
    
  }
  /**
   * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
   */
  private void clearMemory() {  memory_ = null;
    
  }

  public static io.sensory.api.common.SystemSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.sensory.api.common.SystemSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.sensory.api.common.SystemSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.sensory.api.common.SystemSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.sensory.api.common.SystemSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.sensory.api.common.SystemSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.sensory.api.common.SystemSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.sensory.api.common.SystemSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.sensory.api.common.SystemSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.sensory.api.common.SystemSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.sensory.api.common.SystemSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.sensory.api.common.SystemSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.sensory.api.common.SystemSummary prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A summary of system statistics
   * </pre>
   *
   * Protobuf type {@code sensory.api.common.SystemSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.sensory.api.common.SystemSummary, Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.common.SystemSummary)
      io.sensory.api.common.SystemSummaryOrBuilder {
    // Construct using io.sensory.api.common.SystemSummary.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public boolean hasCpu() {
      return instance.hasCpu();
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public io.sensory.api.common.CpuSummary getCpu() {
      return instance.getCpu();
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder setCpu(io.sensory.api.common.CpuSummary value) {
      copyOnWrite();
      instance.setCpu(value);
      return this;
      }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder setCpu(
        io.sensory.api.common.CpuSummary.Builder builderForValue) {
      copyOnWrite();
      instance.setCpu(builderForValue.build());
      return this;
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder mergeCpu(io.sensory.api.common.CpuSummary value) {
      copyOnWrite();
      instance.mergeCpu(value);
      return this;
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder clearCpu() {  copyOnWrite();
      instance.clearCpu();
      return this;
    }

    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public boolean hasMemory() {
      return instance.hasMemory();
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public io.sensory.api.common.MemorySummary getMemory() {
      return instance.getMemory();
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    public Builder setMemory(io.sensory.api.common.MemorySummary value) {
      copyOnWrite();
      instance.setMemory(value);
      return this;
      }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    public Builder setMemory(
        io.sensory.api.common.MemorySummary.Builder builderForValue) {
      copyOnWrite();
      instance.setMemory(builderForValue.build());
      return this;
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    public Builder mergeMemory(io.sensory.api.common.MemorySummary value) {
      copyOnWrite();
      instance.mergeMemory(value);
      return this;
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    public Builder clearMemory() {  copyOnWrite();
      instance.clearMemory();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sensory.api.common.SystemSummary)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.sensory.api.common.SystemSummary();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "cpu_",
            "memory_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\t\u0002\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.sensory.api.common.SystemSummary> parser = PARSER;
        if (parser == null) {
          synchronized (io.sensory.api.common.SystemSummary.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.sensory.api.common.SystemSummary>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sensory.api.common.SystemSummary)
  private static final io.sensory.api.common.SystemSummary DEFAULT_INSTANCE;
  static {
    SystemSummary defaultInstance = new SystemSummary();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SystemSummary.class, defaultInstance);
  }

  public static io.sensory.api.common.SystemSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SystemSummary> PARSER;

  public static com.google.protobuf.Parser<SystemSummary> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

