// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/file/file.proto

package io.sensory.api.v1.file;

/**
 * <pre>
 * A reponse with the file catalog
 * </pre>
 *
 * Protobuf type {@code sensory.api.v1.file.FileCatalogResponse}
 */
public  final class FileCatalogResponse extends
    com.google.protobuf.GeneratedMessageLite<
        FileCatalogResponse, FileCatalogResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:sensory.api.v1.file.FileCatalogResponse)
    FileCatalogResponseOrBuilder {
  private FileCatalogResponse() {
    catalog_ = emptyProtobufList();
  }
  public static final int CATALOG_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<io.sensory.api.v1.file.FileCatalog> catalog_;
  /**
   * <pre>
   * The catalog of files
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.sensory.api.v1.file.FileCatalog> getCatalogList() {
    return catalog_;
  }
  /**
   * <pre>
   * The catalog of files
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
   */
  public java.util.List<? extends io.sensory.api.v1.file.FileCatalogOrBuilder> 
      getCatalogOrBuilderList() {
    return catalog_;
  }
  /**
   * <pre>
   * The catalog of files
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
   */
  @java.lang.Override
  public int getCatalogCount() {
    return catalog_.size();
  }
  /**
   * <pre>
   * The catalog of files
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
   */
  @java.lang.Override
  public io.sensory.api.v1.file.FileCatalog getCatalog(int index) {
    return catalog_.get(index);
  }
  /**
   * <pre>
   * The catalog of files
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
   */
  public io.sensory.api.v1.file.FileCatalogOrBuilder getCatalogOrBuilder(
      int index) {
    return catalog_.get(index);
  }
  private void ensureCatalogIsMutable() {
    com.google.protobuf.Internal.ProtobufList<io.sensory.api.v1.file.FileCatalog> tmp = catalog_;
    if (!tmp.isModifiable()) {
      catalog_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * The catalog of files
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
   */
  private void setCatalog(
      int index, io.sensory.api.v1.file.FileCatalog value) {
    value.getClass();
  ensureCatalogIsMutable();
    catalog_.set(index, value);
  }
  /**
   * <pre>
   * The catalog of files
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
   */
  private void addCatalog(io.sensory.api.v1.file.FileCatalog value) {
    value.getClass();
  ensureCatalogIsMutable();
    catalog_.add(value);
  }
  /**
   * <pre>
   * The catalog of files
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
   */
  private void addCatalog(
      int index, io.sensory.api.v1.file.FileCatalog value) {
    value.getClass();
  ensureCatalogIsMutable();
    catalog_.add(index, value);
  }
  /**
   * <pre>
   * The catalog of files
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
   */
  private void addAllCatalog(
      java.lang.Iterable<? extends io.sensory.api.v1.file.FileCatalog> values) {
    ensureCatalogIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, catalog_);
  }
  /**
   * <pre>
   * The catalog of files
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
   */
  private void clearCatalog() {
    catalog_ = emptyProtobufList();
  }
  /**
   * <pre>
   * The catalog of files
   * </pre>
   *
   * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
   */
  private void removeCatalog(int index) {
    ensureCatalogIsMutable();
    catalog_.remove(index);
  }

  public static io.sensory.api.v1.file.FileCatalogResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.sensory.api.v1.file.FileCatalogResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.sensory.api.v1.file.FileCatalogResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.sensory.api.v1.file.FileCatalogResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.sensory.api.v1.file.FileCatalogResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.sensory.api.v1.file.FileCatalogResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.sensory.api.v1.file.FileCatalogResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.sensory.api.v1.file.FileCatalogResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.sensory.api.v1.file.FileCatalogResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.sensory.api.v1.file.FileCatalogResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.sensory.api.v1.file.FileCatalogResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.sensory.api.v1.file.FileCatalogResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.sensory.api.v1.file.FileCatalogResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A reponse with the file catalog
   * </pre>
   *
   * Protobuf type {@code sensory.api.v1.file.FileCatalogResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.sensory.api.v1.file.FileCatalogResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.v1.file.FileCatalogResponse)
      io.sensory.api.v1.file.FileCatalogResponseOrBuilder {
    // Construct using io.sensory.api.v1.file.FileCatalogResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    @java.lang.Override
    public java.util.List<io.sensory.api.v1.file.FileCatalog> getCatalogList() {
      return java.util.Collections.unmodifiableList(
          instance.getCatalogList());
    }
    /**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    @java.lang.Override
    public int getCatalogCount() {
      return instance.getCatalogCount();
    }/**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    @java.lang.Override
    public io.sensory.api.v1.file.FileCatalog getCatalog(int index) {
      return instance.getCatalog(index);
    }
    /**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    public Builder setCatalog(
        int index, io.sensory.api.v1.file.FileCatalog value) {
      copyOnWrite();
      instance.setCatalog(index, value);
      return this;
    }
    /**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    public Builder setCatalog(
        int index, io.sensory.api.v1.file.FileCatalog.Builder builderForValue) {
      copyOnWrite();
      instance.setCatalog(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    public Builder addCatalog(io.sensory.api.v1.file.FileCatalog value) {
      copyOnWrite();
      instance.addCatalog(value);
      return this;
    }
    /**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    public Builder addCatalog(
        int index, io.sensory.api.v1.file.FileCatalog value) {
      copyOnWrite();
      instance.addCatalog(index, value);
      return this;
    }
    /**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    public Builder addCatalog(
        io.sensory.api.v1.file.FileCatalog.Builder builderForValue) {
      copyOnWrite();
      instance.addCatalog(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    public Builder addCatalog(
        int index, io.sensory.api.v1.file.FileCatalog.Builder builderForValue) {
      copyOnWrite();
      instance.addCatalog(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    public Builder addAllCatalog(
        java.lang.Iterable<? extends io.sensory.api.v1.file.FileCatalog> values) {
      copyOnWrite();
      instance.addAllCatalog(values);
      return this;
    }
    /**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    public Builder clearCatalog() {
      copyOnWrite();
      instance.clearCatalog();
      return this;
    }
    /**
     * <pre>
     * The catalog of files
     * </pre>
     *
     * <code>repeated .sensory.api.v1.file.FileCatalog catalog = 1;</code>
     */
    public Builder removeCatalog(int index) {
      copyOnWrite();
      instance.removeCatalog(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sensory.api.v1.file.FileCatalogResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.sensory.api.v1.file.FileCatalogResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "catalog_",
            io.sensory.api.v1.file.FileCatalog.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.sensory.api.v1.file.FileCatalogResponse> parser = PARSER;
        if (parser == null) {
          synchronized (io.sensory.api.v1.file.FileCatalogResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.sensory.api.v1.file.FileCatalogResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sensory.api.v1.file.FileCatalogResponse)
  private static final io.sensory.api.v1.file.FileCatalogResponse DEFAULT_INSTANCE;
  static {
    FileCatalogResponse defaultInstance = new FileCatalogResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FileCatalogResponse.class, defaultInstance);
  }

  public static io.sensory.api.v1.file.FileCatalogResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FileCatalogResponse> PARSER;

  public static com.google.protobuf.Parser<FileCatalogResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

