// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/file/file.proto

package io.sensory.api.v1.file;

public final class SensoryApiV1FileProto {
  private SensoryApiV1FileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
