// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/video/video.proto

package ai.sensorycloud.api.v1.video;

/**
 * <pre>
 * Provides information for an enrollment
 * </pre>
 *
 * Protobuf type {@code sensory.api.v1.video.CreateEnrollmentConfig}
 */
public  final class CreateEnrollmentConfig extends
    com.google.protobuf.GeneratedMessageLite<
        CreateEnrollmentConfig, CreateEnrollmentConfig.Builder> implements
    // @@protoc_insertion_point(message_implements:sensory.api.v1.video.CreateEnrollmentConfig)
    CreateEnrollmentConfigOrBuilder {
  private CreateEnrollmentConfig() {
    userId_ = "";
    deviceId_ = "";
    modelName_ = "";
    description_ = "";
    referenceId_ = "";
  }
  public static final int USERID_FIELD_NUMBER = 1;
  private java.lang.String userId_;
  /**
   * <pre>
   * The unique user Identifer. This value should be a unique email address or username known by the user.
   * </pre>
   *
   * <code>string userId = 1 [(.validate.rules) = { ... }</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    return userId_;
  }
  /**
   * <pre>
   * The unique user Identifer. This value should be a unique email address or username known by the user.
   * </pre>
   *
   * <code>string userId = 1 [(.validate.rules) = { ... }</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userId_);
  }
  /**
   * <pre>
   * The unique user Identifer. This value should be a unique email address or username known by the user.
   * </pre>
   *
   * <code>string userId = 1 [(.validate.rules) = { ... }</code>
   * @param value The userId to set.
   */
  private void setUserId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    userId_ = value;
  }
  /**
   * <pre>
   * The unique user Identifer. This value should be a unique email address or username known by the user.
   * </pre>
   *
   * <code>string userId = 1 [(.validate.rules) = { ... }</code>
   */
  private void clearUserId() {

    userId_ = getDefaultInstance().getUserId();
  }
  /**
   * <pre>
   * The unique user Identifer. This value should be a unique email address or username known by the user.
   * </pre>
   *
   * <code>string userId = 1 [(.validate.rules) = { ... }</code>
   * @param value The bytes for userId to set.
   */
  private void setUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userId_ = value.toStringUtf8();

  }

  public static final int DEVICEID_FIELD_NUMBER = 2;
  private java.lang.String deviceId_;
  /**
   * <pre>
   * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
   * this value is used to identify a device uniquely across multiple enrollments
   * </pre>
   *
   * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    return deviceId_;
  }
  /**
   * <pre>
   * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
   * this value is used to identify a device uniquely across multiple enrollments
   * </pre>
   *
   * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
  }
  /**
   * <pre>
   * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
   * this value is used to identify a device uniquely across multiple enrollments
   * </pre>
   *
   * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
   * @param value The deviceId to set.
   */
  private void setDeviceId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    deviceId_ = value;
  }
  /**
   * <pre>
   * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
   * this value is used to identify a device uniquely across multiple enrollments
   * </pre>
   *
   * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
   */
  private void clearDeviceId() {

    deviceId_ = getDefaultInstance().getDeviceId();
  }
  /**
   * <pre>
   * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
   * this value is used to identify a device uniquely across multiple enrollments
   * </pre>
   *
   * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
   * @param value The bytes for deviceId to set.
   */
  private void setDeviceIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deviceId_ = value.toStringUtf8();

  }

  public static final int MODELNAME_FIELD_NUMBER = 3;
  private java.lang.String modelName_;
  /**
   * <pre>
   * Name of background model to be enrolled in
   * Background models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
   * @return The modelName.
   */
  @java.lang.Override
  public java.lang.String getModelName() {
    return modelName_;
  }
  /**
   * <pre>
   * Name of background model to be enrolled in
   * Background models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
   * @return The bytes for modelName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(modelName_);
  }
  /**
   * <pre>
   * Name of background model to be enrolled in
   * Background models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
   * @param value The modelName to set.
   */
  private void setModelName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    modelName_ = value;
  }
  /**
   * <pre>
   * Name of background model to be enrolled in
   * Background models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
   */
  private void clearModelName() {

    modelName_ = getDefaultInstance().getModelName();
  }
  /**
   * <pre>
   * Name of background model to be enrolled in
   * Background models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
   * @param value The bytes for modelName to set.
   */
  private void setModelNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    modelName_ = value.toStringUtf8();

  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private java.lang.String description_;
  /**
   * <pre>
   * Description of the enrollment as entered by the user.
   * Max length is 1023 characters
   * </pre>
   *
   * <code>string description = 4 [(.validate.rules) = { ... }</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <pre>
   * Description of the enrollment as entered by the user.
   * Max length is 1023 characters
   * </pre>
   *
   * <code>string description = 4 [(.validate.rules) = { ... }</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <pre>
   * Description of the enrollment as entered by the user.
   * Max length is 1023 characters
   * </pre>
   *
   * <code>string description = 4 [(.validate.rules) = { ... }</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <pre>
   * Description of the enrollment as entered by the user.
   * Max length is 1023 characters
   * </pre>
   *
   * <code>string description = 4 [(.validate.rules) = { ... }</code>
   */
  private void clearDescription() {

    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <pre>
   * Description of the enrollment as entered by the user.
   * Max length is 1023 characters
   * </pre>
   *
   * <code>string description = 4 [(.validate.rules) = { ... }</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();

  }

  public static final int ISLIVENESSENABLED_FIELD_NUMBER = 5;
  private boolean isLivenessEnabled_;
  /**
   * <pre>
   * Enable a liveness check on the image, which will further improve the security of enrollment at the expense of a slightly slower response.
   * </pre>
   *
   * <code>bool isLivenessEnabled = 5;</code>
   * @return The isLivenessEnabled.
   */
  @java.lang.Override
  public boolean getIsLivenessEnabled() {
    return isLivenessEnabled_;
  }
  /**
   * <pre>
   * Enable a liveness check on the image, which will further improve the security of enrollment at the expense of a slightly slower response.
   * </pre>
   *
   * <code>bool isLivenessEnabled = 5;</code>
   * @param value The isLivenessEnabled to set.
   */
  private void setIsLivenessEnabled(boolean value) {
    
    isLivenessEnabled_ = value;
  }
  /**
   * <pre>
   * Enable a liveness check on the image, which will further improve the security of enrollment at the expense of a slightly slower response.
   * </pre>
   *
   * <code>bool isLivenessEnabled = 5;</code>
   */
  private void clearIsLivenessEnabled() {

    isLivenessEnabled_ = false;
  }

  public static final int LIVENESSTHRESHOLD_FIELD_NUMBER = 6;
  private int livenessThreshold_;
  /**
   * <pre>
   * The liveness threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
   * @return The enum numeric value on the wire for livenessThreshold.
   */
  @java.lang.Override
  public int getLivenessThresholdValue() {
    return livenessThreshold_;
  }
  /**
   * <pre>
   * The liveness threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
   * @return The livenessThreshold.
   */
  @java.lang.Override
  public ai.sensorycloud.api.v1.video.RecognitionThreshold getLivenessThreshold() {
    ai.sensorycloud.api.v1.video.RecognitionThreshold result = ai.sensorycloud.api.v1.video.RecognitionThreshold.forNumber(livenessThreshold_);
    return result == null ? ai.sensorycloud.api.v1.video.RecognitionThreshold.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * The liveness threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
   * @param value The enum numeric value on the wire for livenessThreshold to set.
   */
  private void setLivenessThresholdValue(int value) {
      livenessThreshold_ = value;
  }
  /**
   * <pre>
   * The liveness threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
   * @param value The livenessThreshold to set.
   */
  private void setLivenessThreshold(ai.sensorycloud.api.v1.video.RecognitionThreshold value) {
    livenessThreshold_ = value.getNumber();

  }
  /**
   * <pre>
   * The liveness threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
   */
  private void clearLivenessThreshold() {

    livenessThreshold_ = 0;
  }

  public static final int COMPRESSION_FIELD_NUMBER = 7;
  private ai.sensorycloud.api.common.CompressionConfiguration compression_;
  /**
   * <pre>
   * Information about how the video data will be compressed.
   * </pre>
   *
   * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
   */
  @java.lang.Override
  public boolean hasCompression() {
    return compression_ != null;
  }
  /**
   * <pre>
   * Information about how the video data will be compressed.
   * </pre>
   *
   * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.CompressionConfiguration getCompression() {
    return compression_ == null ? ai.sensorycloud.api.common.CompressionConfiguration.getDefaultInstance() : compression_;
  }
  /**
   * <pre>
   * Information about how the video data will be compressed.
   * </pre>
   *
   * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
   */
  private void setCompression(ai.sensorycloud.api.common.CompressionConfiguration value) {
    value.getClass();
  compression_ = value;

    }
  /**
   * <pre>
   * Information about how the video data will be compressed.
   * </pre>
   *
   * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeCompression(ai.sensorycloud.api.common.CompressionConfiguration value) {
    value.getClass();
  if (compression_ != null &&
        compression_ != ai.sensorycloud.api.common.CompressionConfiguration.getDefaultInstance()) {
      compression_ =
        ai.sensorycloud.api.common.CompressionConfiguration.newBuilder(compression_).mergeFrom(value).buildPartial();
    } else {
      compression_ = value;
    }

  }
  /**
   * <pre>
   * Information about how the video data will be compressed.
   * </pre>
   *
   * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
   */
  private void clearCompression() {  compression_ = null;

  }

  public static final int REFERENCEID_FIELD_NUMBER = 8;
  private java.lang.String referenceId_;
  /**
   * <pre>
   * Reference Id allows clients to assign their own identifier to enrollments for various purposes
   * such as tying an audio and video enrollment together.
   * </pre>
   *
   * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
   * @return The referenceId.
   */
  @java.lang.Override
  public java.lang.String getReferenceId() {
    return referenceId_;
  }
  /**
   * <pre>
   * Reference Id allows clients to assign their own identifier to enrollments for various purposes
   * such as tying an audio and video enrollment together.
   * </pre>
   *
   * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
   * @return The bytes for referenceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReferenceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(referenceId_);
  }
  /**
   * <pre>
   * Reference Id allows clients to assign their own identifier to enrollments for various purposes
   * such as tying an audio and video enrollment together.
   * </pre>
   *
   * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
   * @param value The referenceId to set.
   */
  private void setReferenceId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    referenceId_ = value;
  }
  /**
   * <pre>
   * Reference Id allows clients to assign their own identifier to enrollments for various purposes
   * such as tying an audio and video enrollment together.
   * </pre>
   *
   * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
   */
  private void clearReferenceId() {

    referenceId_ = getDefaultInstance().getReferenceId();
  }
  /**
   * <pre>
   * Reference Id allows clients to assign their own identifier to enrollments for various purposes
   * such as tying an audio and video enrollment together.
   * </pre>
   *
   * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
   * @param value The bytes for referenceId to set.
   */
  private void setReferenceIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    referenceId_ = value.toStringUtf8();

  }

  public static final int NUMLIVENESSFRAMESREQUIRED_FIELD_NUMBER = 9;
  private int numLivenessFramesRequired_;
  /**
   * <pre>
   * If isLivenessEnabled is true, this determines how many frames need to pass the liveness check before the enrollment can be successful
   * A value of 0 means that all enrollment frames must pass the liveness check.
   * </pre>
   *
   * <code>int32 numLivenessFramesRequired = 9;</code>
   * @return The numLivenessFramesRequired.
   */
  @java.lang.Override
  public int getNumLivenessFramesRequired() {
    return numLivenessFramesRequired_;
  }
  /**
   * <pre>
   * If isLivenessEnabled is true, this determines how many frames need to pass the liveness check before the enrollment can be successful
   * A value of 0 means that all enrollment frames must pass the liveness check.
   * </pre>
   *
   * <code>int32 numLivenessFramesRequired = 9;</code>
   * @param value The numLivenessFramesRequired to set.
   */
  private void setNumLivenessFramesRequired(int value) {
    
    numLivenessFramesRequired_ = value;
  }
  /**
   * <pre>
   * If isLivenessEnabled is true, this determines how many frames need to pass the liveness check before the enrollment can be successful
   * A value of 0 means that all enrollment frames must pass the liveness check.
   * </pre>
   *
   * <code>int32 numLivenessFramesRequired = 9;</code>
   */
  private void clearNumLivenessFramesRequired() {

    numLivenessFramesRequired_ = 0;
  }

  public static final int DISABLESERVERENROLLMENTTEMPLATESTORAGE_FIELD_NUMBER = 10;
  private boolean disableServerEnrollmentTemplateStorage_;
  /**
   * <pre>
   * Prevent the server from storing the enrollment template. The template will be returned to the client for storage.
   * </pre>
   *
   * <code>bool disableServerEnrollmentTemplateStorage = 10;</code>
   * @return The disableServerEnrollmentTemplateStorage.
   */
  @java.lang.Override
  public boolean getDisableServerEnrollmentTemplateStorage() {
    return disableServerEnrollmentTemplateStorage_;
  }
  /**
   * <pre>
   * Prevent the server from storing the enrollment template. The template will be returned to the client for storage.
   * </pre>
   *
   * <code>bool disableServerEnrollmentTemplateStorage = 10;</code>
   * @param value The disableServerEnrollmentTemplateStorage to set.
   */
  private void setDisableServerEnrollmentTemplateStorage(boolean value) {
    
    disableServerEnrollmentTemplateStorage_ = value;
  }
  /**
   * <pre>
   * Prevent the server from storing the enrollment template. The template will be returned to the client for storage.
   * </pre>
   *
   * <code>bool disableServerEnrollmentTemplateStorage = 10;</code>
   */
  private void clearDisableServerEnrollmentTemplateStorage() {

    disableServerEnrollmentTemplateStorage_ = false;
  }

  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.v1.video.CreateEnrollmentConfig prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Provides information for an enrollment
   * </pre>
   *
   * Protobuf type {@code sensory.api.v1.video.CreateEnrollmentConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ai.sensorycloud.api.v1.video.CreateEnrollmentConfig, Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.v1.video.CreateEnrollmentConfig)
      ai.sensorycloud.api.v1.video.CreateEnrollmentConfigOrBuilder {
    // Construct using ai.sensorycloud.api.v1.video.CreateEnrollmentConfig.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The unique user Identifer. This value should be a unique email address or username known by the user.
     * </pre>
     *
     * <code>string userId = 1 [(.validate.rules) = { ... }</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      return instance.getUserId();
    }
    /**
     * <pre>
     * The unique user Identifer. This value should be a unique email address or username known by the user.
     * </pre>
     *
     * <code>string userId = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return instance.getUserIdBytes();
    }
    /**
     * <pre>
     * The unique user Identifer. This value should be a unique email address or username known by the user.
     * </pre>
     *
     * <code>string userId = 1 [(.validate.rules) = { ... }</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <pre>
     * The unique user Identifer. This value should be a unique email address or username known by the user.
     * </pre>
     *
     * <code>string userId = 1 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }
    /**
     * <pre>
     * The unique user Identifer. This value should be a unique email address or username known by the user.
     * </pre>
     *
     * <code>string userId = 1 [(.validate.rules) = { ... }</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
     * this value is used to identify a device uniquely across multiple enrollments
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <pre>
     * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
     * this value is used to identify a device uniquely across multiple enrollments
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return instance.getDeviceIdBytes();
    }
    /**
     * <pre>
     * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
     * this value is used to identify a device uniquely across multiple enrollments
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <pre>
     * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
     * this value is used to identify a device uniquely across multiple enrollments
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }
    /**
     * <pre>
     * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
     * this value is used to identify a device uniquely across multiple enrollments
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Name of background model to be enrolled in
     * Background models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
     * @return The modelName.
     */
    @java.lang.Override
    public java.lang.String getModelName() {
      return instance.getModelName();
    }
    /**
     * <pre>
     * Name of background model to be enrolled in
     * Background models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for modelName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      return instance.getModelNameBytes();
    }
    /**
     * <pre>
     * Name of background model to be enrolled in
     * Background models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
     * @param value The modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelName(
        java.lang.String value) {
      copyOnWrite();
      instance.setModelName(value);
      return this;
    }
    /**
     * <pre>
     * Name of background model to be enrolled in
     * Background models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearModelName() {
      copyOnWrite();
      instance.clearModelName();
      return this;
    }
    /**
     * <pre>
     * Name of background model to be enrolled in
     * Background models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
     * @param value The bytes for modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setModelNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * Description of the enrollment as entered by the user.
     * Max length is 1023 characters
     * </pre>
     *
     * <code>string description = 4 [(.validate.rules) = { ... }</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <pre>
     * Description of the enrollment as entered by the user.
     * Max length is 1023 characters
     * </pre>
     *
     * <code>string description = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <pre>
     * Description of the enrollment as entered by the user.
     * Max length is 1023 characters
     * </pre>
     *
     * <code>string description = 4 [(.validate.rules) = { ... }</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <pre>
     * Description of the enrollment as entered by the user.
     * Max length is 1023 characters
     * </pre>
     *
     * <code>string description = 4 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <pre>
     * Description of the enrollment as entered by the user.
     * Max length is 1023 characters
     * </pre>
     *
     * <code>string description = 4 [(.validate.rules) = { ... }</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <pre>
     * Enable a liveness check on the image, which will further improve the security of enrollment at the expense of a slightly slower response.
     * </pre>
     *
     * <code>bool isLivenessEnabled = 5;</code>
     * @return The isLivenessEnabled.
     */
    @java.lang.Override
    public boolean getIsLivenessEnabled() {
      return instance.getIsLivenessEnabled();
    }
    /**
     * <pre>
     * Enable a liveness check on the image, which will further improve the security of enrollment at the expense of a slightly slower response.
     * </pre>
     *
     * <code>bool isLivenessEnabled = 5;</code>
     * @param value The isLivenessEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setIsLivenessEnabled(boolean value) {
      copyOnWrite();
      instance.setIsLivenessEnabled(value);
      return this;
    }
    /**
     * <pre>
     * Enable a liveness check on the image, which will further improve the security of enrollment at the expense of a slightly slower response.
     * </pre>
     *
     * <code>bool isLivenessEnabled = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsLivenessEnabled() {
      copyOnWrite();
      instance.clearIsLivenessEnabled();
      return this;
    }

    /**
     * <pre>
     * The liveness threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
     * @return The enum numeric value on the wire for livenessThreshold.
     */
    @java.lang.Override
    public int getLivenessThresholdValue() {
      return instance.getLivenessThresholdValue();
    }
    /**
     * <pre>
     * The liveness threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
     * @param value The livenessThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setLivenessThresholdValue(int value) {
      copyOnWrite();
      instance.setLivenessThresholdValue(value);
      return this;
    }
    /**
     * <pre>
     * The liveness threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
     * @return The livenessThreshold.
     */
    @java.lang.Override
    public ai.sensorycloud.api.v1.video.RecognitionThreshold getLivenessThreshold() {
      return instance.getLivenessThreshold();
    }
    /**
     * <pre>
     * The liveness threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
     * @param value The enum numeric value on the wire for livenessThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setLivenessThreshold(ai.sensorycloud.api.v1.video.RecognitionThreshold value) {
      copyOnWrite();
      instance.setLivenessThreshold(value);
      return this;
    }
    /**
     * <pre>
     * The liveness threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearLivenessThreshold() {
      copyOnWrite();
      instance.clearLivenessThreshold();
      return this;
    }

    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    @java.lang.Override
    public boolean hasCompression() {
      return instance.hasCompression();
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    @java.lang.Override
    public ai.sensorycloud.api.common.CompressionConfiguration getCompression() {
      return instance.getCompression();
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    public Builder setCompression(ai.sensorycloud.api.common.CompressionConfiguration value) {
      copyOnWrite();
      instance.setCompression(value);
      return this;
      }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    public Builder setCompression(
        ai.sensorycloud.api.common.CompressionConfiguration.Builder builderForValue) {
      copyOnWrite();
      instance.setCompression(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    public Builder mergeCompression(ai.sensorycloud.api.common.CompressionConfiguration value) {
      copyOnWrite();
      instance.mergeCompression(value);
      return this;
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    public Builder clearCompression() {  copyOnWrite();
      instance.clearCompression();
      return this;
    }

    /**
     * <pre>
     * Reference Id allows clients to assign their own identifier to enrollments for various purposes
     * such as tying an audio and video enrollment together.
     * </pre>
     *
     * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
     * @return The referenceId.
     */
    @java.lang.Override
    public java.lang.String getReferenceId() {
      return instance.getReferenceId();
    }
    /**
     * <pre>
     * Reference Id allows clients to assign their own identifier to enrollments for various purposes
     * such as tying an audio and video enrollment together.
     * </pre>
     *
     * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
     * @return The bytes for referenceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReferenceIdBytes() {
      return instance.getReferenceIdBytes();
    }
    /**
     * <pre>
     * Reference Id allows clients to assign their own identifier to enrollments for various purposes
     * such as tying an audio and video enrollment together.
     * </pre>
     *
     * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
     * @param value The referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setReferenceId(value);
      return this;
    }
    /**
     * <pre>
     * Reference Id allows clients to assign their own identifier to enrollments for various purposes
     * such as tying an audio and video enrollment together.
     * </pre>
     *
     * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceId() {
      copyOnWrite();
      instance.clearReferenceId();
      return this;
    }
    /**
     * <pre>
     * Reference Id allows clients to assign their own identifier to enrollments for various purposes
     * such as tying an audio and video enrollment together.
     * </pre>
     *
     * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
     * @param value The bytes for referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReferenceIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * If isLivenessEnabled is true, this determines how many frames need to pass the liveness check before the enrollment can be successful
     * A value of 0 means that all enrollment frames must pass the liveness check.
     * </pre>
     *
     * <code>int32 numLivenessFramesRequired = 9;</code>
     * @return The numLivenessFramesRequired.
     */
    @java.lang.Override
    public int getNumLivenessFramesRequired() {
      return instance.getNumLivenessFramesRequired();
    }
    /**
     * <pre>
     * If isLivenessEnabled is true, this determines how many frames need to pass the liveness check before the enrollment can be successful
     * A value of 0 means that all enrollment frames must pass the liveness check.
     * </pre>
     *
     * <code>int32 numLivenessFramesRequired = 9;</code>
     * @param value The numLivenessFramesRequired to set.
     * @return This builder for chaining.
     */
    public Builder setNumLivenessFramesRequired(int value) {
      copyOnWrite();
      instance.setNumLivenessFramesRequired(value);
      return this;
    }
    /**
     * <pre>
     * If isLivenessEnabled is true, this determines how many frames need to pass the liveness check before the enrollment can be successful
     * A value of 0 means that all enrollment frames must pass the liveness check.
     * </pre>
     *
     * <code>int32 numLivenessFramesRequired = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumLivenessFramesRequired() {
      copyOnWrite();
      instance.clearNumLivenessFramesRequired();
      return this;
    }

    /**
     * <pre>
     * Prevent the server from storing the enrollment template. The template will be returned to the client for storage.
     * </pre>
     *
     * <code>bool disableServerEnrollmentTemplateStorage = 10;</code>
     * @return The disableServerEnrollmentTemplateStorage.
     */
    @java.lang.Override
    public boolean getDisableServerEnrollmentTemplateStorage() {
      return instance.getDisableServerEnrollmentTemplateStorage();
    }
    /**
     * <pre>
     * Prevent the server from storing the enrollment template. The template will be returned to the client for storage.
     * </pre>
     *
     * <code>bool disableServerEnrollmentTemplateStorage = 10;</code>
     * @param value The disableServerEnrollmentTemplateStorage to set.
     * @return This builder for chaining.
     */
    public Builder setDisableServerEnrollmentTemplateStorage(boolean value) {
      copyOnWrite();
      instance.setDisableServerEnrollmentTemplateStorage(value);
      return this;
    }
    /**
     * <pre>
     * Prevent the server from storing the enrollment template. The template will be returned to the client for storage.
     * </pre>
     *
     * <code>bool disableServerEnrollmentTemplateStorage = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisableServerEnrollmentTemplateStorage() {
      copyOnWrite();
      instance.clearDisableServerEnrollmentTemplateStorage();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sensory.api.v1.video.CreateEnrollmentConfig)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ai.sensorycloud.api.v1.video.CreateEnrollmentConfig();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "userId_",
            "deviceId_",
            "modelName_",
            "description_",
            "isLivenessEnabled_",
            "livenessThreshold_",
            "compression_",
            "referenceId_",
            "numLivenessFramesRequired_",
            "disableServerEnrollmentTemplateStorage_",
          };
          java.lang.String info =
              "\u0000\n\u0000\u0000\u0001\n\n\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\u0208\u0005\u0007\u0006\f\u0007\t\b\u0208\t\u0004\n\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ai.sensorycloud.api.v1.video.CreateEnrollmentConfig> parser = PARSER;
        if (parser == null) {
          synchronized (ai.sensorycloud.api.v1.video.CreateEnrollmentConfig.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ai.sensorycloud.api.v1.video.CreateEnrollmentConfig>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sensory.api.v1.video.CreateEnrollmentConfig)
  private static final ai.sensorycloud.api.v1.video.CreateEnrollmentConfig DEFAULT_INSTANCE;
  static {
    CreateEnrollmentConfig defaultInstance = new CreateEnrollmentConfig();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CreateEnrollmentConfig.class, defaultInstance);
  }

  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CreateEnrollmentConfig> PARSER;

  public static com.google.protobuf.Parser<CreateEnrollmentConfig> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

