// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/video/video.proto

package ai.sensorycloud.api.v1.video;

/**
 * <pre>
 * Provides information for a video-based event recognition
 * </pre>
 *
 * Protobuf type {@code sensory.api.v1.video.ValidateRecognitionConfig}
 */
public  final class ValidateRecognitionConfig extends
    com.google.protobuf.GeneratedMessageLite<
        ValidateRecognitionConfig, ValidateRecognitionConfig.Builder> implements
    // @@protoc_insertion_point(message_implements:sensory.api.v1.video.ValidateRecognitionConfig)
    ValidateRecognitionConfigOrBuilder {
  private ValidateRecognitionConfig() {
    modelName_ = "";
    userId_ = "";
  }
  public static final int MODELNAME_FIELD_NUMBER = 1;
  private java.lang.String modelName_;
  /**
   * <pre>
   * Name of model to validate against
   * Models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 1 [(.validate.rules) = { ... }</code>
   * @return The modelName.
   */
  @java.lang.Override
  public java.lang.String getModelName() {
    return modelName_;
  }
  /**
   * <pre>
   * Name of model to validate against
   * Models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 1 [(.validate.rules) = { ... }</code>
   * @return The bytes for modelName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(modelName_);
  }
  /**
   * <pre>
   * Name of model to validate against
   * Models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 1 [(.validate.rules) = { ... }</code>
   * @param value The modelName to set.
   */
  private void setModelName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    modelName_ = value;
  }
  /**
   * <pre>
   * Name of model to validate against
   * Models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 1 [(.validate.rules) = { ... }</code>
   */
  private void clearModelName() {
    
    modelName_ = getDefaultInstance().getModelName();
  }
  /**
   * <pre>
   * Name of model to validate against
   * Models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 1 [(.validate.rules) = { ... }</code>
   * @param value The bytes for modelName to set.
   */
  private void setModelNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    modelName_ = value.toStringUtf8();
    
  }

  public static final int USERID_FIELD_NUMBER = 2;
  private java.lang.String userId_;
  /**
   * <pre>
   * The unique user Identifer
   * </pre>
   *
   * <code>string userId = 2 [(.validate.rules) = { ... }</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    return userId_;
  }
  /**
   * <pre>
   * The unique user Identifer
   * </pre>
   *
   * <code>string userId = 2 [(.validate.rules) = { ... }</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userId_);
  }
  /**
   * <pre>
   * The unique user Identifer
   * </pre>
   *
   * <code>string userId = 2 [(.validate.rules) = { ... }</code>
   * @param value The userId to set.
   */
  private void setUserId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    userId_ = value;
  }
  /**
   * <pre>
   * The unique user Identifer
   * </pre>
   *
   * <code>string userId = 2 [(.validate.rules) = { ... }</code>
   */
  private void clearUserId() {
    
    userId_ = getDefaultInstance().getUserId();
  }
  /**
   * <pre>
   * The unique user Identifer
   * </pre>
   *
   * <code>string userId = 2 [(.validate.rules) = { ... }</code>
   * @param value The bytes for userId to set.
   */
  private void setUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userId_ = value.toStringUtf8();
    
  }

  public static final int THRESHOLD_FIELD_NUMBER = 3;
  private int threshold_;
  /**
   * <pre>
   * The model threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold threshold = 3 [(.validate.rules) = { ... }</code>
   * @return The enum numeric value on the wire for threshold.
   */
  @java.lang.Override
  public int getThresholdValue() {
    return threshold_;
  }
  /**
   * <pre>
   * The model threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold threshold = 3 [(.validate.rules) = { ... }</code>
   * @return The threshold.
   */
  @java.lang.Override
  public ai.sensorycloud.api.v1.video.RecognitionThreshold getThreshold() {
    ai.sensorycloud.api.v1.video.RecognitionThreshold result = ai.sensorycloud.api.v1.video.RecognitionThreshold.forNumber(threshold_);
    return result == null ? ai.sensorycloud.api.v1.video.RecognitionThreshold.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * The model threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold threshold = 3 [(.validate.rules) = { ... }</code>
   * @param value The enum numeric value on the wire for threshold to set.
   */
  private void setThresholdValue(int value) {
      threshold_ = value;
  }
  /**
   * <pre>
   * The model threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold threshold = 3 [(.validate.rules) = { ... }</code>
   * @param value The threshold to set.
   */
  private void setThreshold(ai.sensorycloud.api.v1.video.RecognitionThreshold value) {
    threshold_ = value.getNumber();
    
  }
  /**
   * <pre>
   * The model threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold threshold = 3 [(.validate.rules) = { ... }</code>
   */
  private void clearThreshold() {
    
    threshold_ = 0;
  }

  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.v1.video.ValidateRecognitionConfig prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Provides information for a video-based event recognition
   * </pre>
   *
   * Protobuf type {@code sensory.api.v1.video.ValidateRecognitionConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ai.sensorycloud.api.v1.video.ValidateRecognitionConfig, Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.v1.video.ValidateRecognitionConfig)
      ai.sensorycloud.api.v1.video.ValidateRecognitionConfigOrBuilder {
    // Construct using ai.sensorycloud.api.v1.video.ValidateRecognitionConfig.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Name of model to validate against
     * Models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 1 [(.validate.rules) = { ... }</code>
     * @return The modelName.
     */
    @java.lang.Override
    public java.lang.String getModelName() {
      return instance.getModelName();
    }
    /**
     * <pre>
     * Name of model to validate against
     * Models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for modelName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      return instance.getModelNameBytes();
    }
    /**
     * <pre>
     * Name of model to validate against
     * Models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 1 [(.validate.rules) = { ... }</code>
     * @param value The modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelName(
        java.lang.String value) {
      copyOnWrite();
      instance.setModelName(value);
      return this;
    }
    /**
     * <pre>
     * Name of model to validate against
     * Models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 1 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearModelName() {
      copyOnWrite();
      instance.clearModelName();
      return this;
    }
    /**
     * <pre>
     * Name of model to validate against
     * Models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 1 [(.validate.rules) = { ... }</code>
     * @param value The bytes for modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setModelNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * The unique user Identifer
     * </pre>
     *
     * <code>string userId = 2 [(.validate.rules) = { ... }</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      return instance.getUserId();
    }
    /**
     * <pre>
     * The unique user Identifer
     * </pre>
     *
     * <code>string userId = 2 [(.validate.rules) = { ... }</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return instance.getUserIdBytes();
    }
    /**
     * <pre>
     * The unique user Identifer
     * </pre>
     *
     * <code>string userId = 2 [(.validate.rules) = { ... }</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <pre>
     * The unique user Identifer
     * </pre>
     *
     * <code>string userId = 2 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }
    /**
     * <pre>
     * The unique user Identifer
     * </pre>
     *
     * <code>string userId = 2 [(.validate.rules) = { ... }</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * The model threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold threshold = 3 [(.validate.rules) = { ... }</code>
     * @return The enum numeric value on the wire for threshold.
     */
    @java.lang.Override
    public int getThresholdValue() {
      return instance.getThresholdValue();
    }
    /**
     * <pre>
     * The model threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold threshold = 3 [(.validate.rules) = { ... }</code>
     * @param value The threshold to set.
     * @return This builder for chaining.
     */
    public Builder setThresholdValue(int value) {
      copyOnWrite();
      instance.setThresholdValue(value);
      return this;
    }
    /**
     * <pre>
     * The model threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold threshold = 3 [(.validate.rules) = { ... }</code>
     * @return The threshold.
     */
    @java.lang.Override
    public ai.sensorycloud.api.v1.video.RecognitionThreshold getThreshold() {
      return instance.getThreshold();
    }
    /**
     * <pre>
     * The model threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold threshold = 3 [(.validate.rules) = { ... }</code>
     * @param value The enum numeric value on the wire for threshold to set.
     * @return This builder for chaining.
     */
    public Builder setThreshold(ai.sensorycloud.api.v1.video.RecognitionThreshold value) {
      copyOnWrite();
      instance.setThreshold(value);
      return this;
    }
    /**
     * <pre>
     * The model threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold threshold = 3 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearThreshold() {
      copyOnWrite();
      instance.clearThreshold();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sensory.api.v1.video.ValidateRecognitionConfig)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ai.sensorycloud.api.v1.video.ValidateRecognitionConfig();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "modelName_",
            "userId_",
            "threshold_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ai.sensorycloud.api.v1.video.ValidateRecognitionConfig> parser = PARSER;
        if (parser == null) {
          synchronized (ai.sensorycloud.api.v1.video.ValidateRecognitionConfig.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ai.sensorycloud.api.v1.video.ValidateRecognitionConfig>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sensory.api.v1.video.ValidateRecognitionConfig)
  private static final ai.sensorycloud.api.v1.video.ValidateRecognitionConfig DEFAULT_INSTANCE;
  static {
    ValidateRecognitionConfig defaultInstance = new ValidateRecognitionConfig();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ValidateRecognitionConfig.class, defaultInstance);
  }

  public static ai.sensorycloud.api.v1.video.ValidateRecognitionConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ValidateRecognitionConfig> PARSER;

  public static com.google.protobuf.Parser<ValidateRecognitionConfig> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

