// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/common.proto

package ai.sensorycloud.api.common;

public interface EnrollmentTokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensory.api.common.EnrollmentToken)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Encrypted token containing enrollment information
   * </pre>
   *
   * <code>bytes token = 1;</code>
   * @return The token.
   */
  com.google.protobuf.ByteString getToken();

  /**
   * <pre>
   * The number of seconds until the enrollment token expires
   * </pre>
   *
   * <code>int64 expiration = 2;</code>
   * @return The expiration.
   */
  long getExpiration();
}
