// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/common.proto

package ai.sensorycloud.api.common;

/**
 * <pre>
 * A message for the server to tell how the data has been paginated
 * </pre>
 *
 * Protobuf type {@code sensory.api.common.PaginationResponse}
 */
public  final class PaginationResponse extends
    com.google.protobuf.GeneratedMessageLite<
        PaginationResponse, PaginationResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:sensory.api.common.PaginationResponse)
    PaginationResponseOrBuilder {
  private PaginationResponse() {
    ordering_ = "";
    possibleOrderings_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int ORDERING_FIELD_NUMBER = 1;
  private java.lang.String ordering_;
  /**
   * <pre>
   * The parameter by which the data has been ordered by
   * </pre>
   *
   * <code>string ordering = 1;</code>
   * @return The ordering.
   */
  @java.lang.Override
  public java.lang.String getOrdering() {
    return ordering_;
  }
  /**
   * <pre>
   * The parameter by which the data has been ordered by
   * </pre>
   *
   * <code>string ordering = 1;</code>
   * @return The bytes for ordering.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrderingBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(ordering_);
  }
  /**
   * <pre>
   * The parameter by which the data has been ordered by
   * </pre>
   *
   * <code>string ordering = 1;</code>
   * @param value The ordering to set.
   */
  private void setOrdering(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    ordering_ = value;
  }
  /**
   * <pre>
   * The parameter by which the data has been ordered by
   * </pre>
   *
   * <code>string ordering = 1;</code>
   */
  private void clearOrdering() {

    ordering_ = getDefaultInstance().getOrdering();
  }
  /**
   * <pre>
   * The parameter by which the data has been ordered by
   * </pre>
   *
   * <code>string ordering = 1;</code>
   * @param value The bytes for ordering to set.
   */
  private void setOrderingBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ordering_ = value.toStringUtf8();

  }

  public static final int DECENDING_FIELD_NUMBER = 2;
  private boolean decending_;
  /**
   * <pre>
   * "True" if the data has been sorted in decending order
   * </pre>
   *
   * <code>bool decending = 2;</code>
   * @return The decending.
   */
  @java.lang.Override
  public boolean getDecending() {
    return decending_;
  }
  /**
   * <pre>
   * "True" if the data has been sorted in decending order
   * </pre>
   *
   * <code>bool decending = 2;</code>
   * @param value The decending to set.
   */
  private void setDecending(boolean value) {
    
    decending_ = value;
  }
  /**
   * <pre>
   * "True" if the data has been sorted in decending order
   * </pre>
   *
   * <code>bool decending = 2;</code>
   */
  private void clearDecending() {

    decending_ = false;
  }

  public static final int POSSIBLEORDERINGS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> possibleOrderings_;
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @return A list containing the possibleOrderings.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getPossibleOrderingsList() {
    return possibleOrderings_;
  }
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @return The count of possibleOrderings.
   */
  @java.lang.Override
  public int getPossibleOrderingsCount() {
    return possibleOrderings_.size();
  }
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @param index The index of the element to return.
   * @return The possibleOrderings at the given index.
   */
  @java.lang.Override
  public java.lang.String getPossibleOrderings(int index) {
    return possibleOrderings_.get(index);
  }
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the possibleOrderings at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPossibleOrderingsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        possibleOrderings_.get(index));
  }
  private void ensurePossibleOrderingsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        possibleOrderings_;  if (!tmp.isModifiable()) {
      possibleOrderings_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @param index The index to set the value at.
   * @param value The possibleOrderings to set.
   */
  private void setPossibleOrderings(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensurePossibleOrderingsIsMutable();
    possibleOrderings_.set(index, value);
  }
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @param value The possibleOrderings to add.
   */
  private void addPossibleOrderings(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensurePossibleOrderingsIsMutable();
    possibleOrderings_.add(value);
  }
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @param values The possibleOrderings to add.
   */
  private void addAllPossibleOrderings(
      java.lang.Iterable<java.lang.String> values) {
    ensurePossibleOrderingsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, possibleOrderings_);
  }
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   */
  private void clearPossibleOrderings() {
    possibleOrderings_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @param value The bytes of the possibleOrderings to add.
   */
  private void addPossibleOrderingsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensurePossibleOrderingsIsMutable();
    possibleOrderings_.add(value.toStringUtf8());
  }

  public static final int TOTALCOUNT_FIELD_NUMBER = 4;
  private long totalCount_;
  /**
   * <pre>
   * The total count of data objects
   * </pre>
   *
   * <code>int64 totalCount = 4;</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public long getTotalCount() {
    return totalCount_;
  }
  /**
   * <pre>
   * The total count of data objects
   * </pre>
   *
   * <code>int64 totalCount = 4;</code>
   * @param value The totalCount to set.
   */
  private void setTotalCount(long value) {
    
    totalCount_ = value;
  }
  /**
   * <pre>
   * The total count of data objects
   * </pre>
   *
   * <code>int64 totalCount = 4;</code>
   */
  private void clearTotalCount() {

    totalCount_ = 0L;
  }

  public static final int PAGESIZE_FIELD_NUMBER = 5;
  private int pageSize_;
  /**
   * <pre>
   * The page size of the data
   * </pre>
   *
   * <code>int32 pageSize = 5;</code>
   * @return The pageSize.
   */
  @java.lang.Override
  public int getPageSize() {
    return pageSize_;
  }
  /**
   * <pre>
   * The page size of the data
   * </pre>
   *
   * <code>int32 pageSize = 5;</code>
   * @param value The pageSize to set.
   */
  private void setPageSize(int value) {
    
    pageSize_ = value;
  }
  /**
   * <pre>
   * The page size of the data
   * </pre>
   *
   * <code>int32 pageSize = 5;</code>
   */
  private void clearPageSize() {

    pageSize_ = 0;
  }

  public static final int PREVPAGEINDEX_FIELD_NUMBER = 6;
  private int prevPageIndex_;
  /**
   * <pre>
   * The page index for the previous page. If negative there is no previous page
   * </pre>
   *
   * <code>int32 prevPageIndex = 6;</code>
   * @return The prevPageIndex.
   */
  @java.lang.Override
  public int getPrevPageIndex() {
    return prevPageIndex_;
  }
  /**
   * <pre>
   * The page index for the previous page. If negative there is no previous page
   * </pre>
   *
   * <code>int32 prevPageIndex = 6;</code>
   * @param value The prevPageIndex to set.
   */
  private void setPrevPageIndex(int value) {
    
    prevPageIndex_ = value;
  }
  /**
   * <pre>
   * The page index for the previous page. If negative there is no previous page
   * </pre>
   *
   * <code>int32 prevPageIndex = 6;</code>
   */
  private void clearPrevPageIndex() {

    prevPageIndex_ = 0;
  }

  public static final int CURRENTPAGEINDEX_FIELD_NUMBER = 7;
  private int currentPageIndex_;
  /**
   * <pre>
   * The page index for the current page.
   * </pre>
   *
   * <code>int32 currentPageIndex = 7;</code>
   * @return The currentPageIndex.
   */
  @java.lang.Override
  public int getCurrentPageIndex() {
    return currentPageIndex_;
  }
  /**
   * <pre>
   * The page index for the current page.
   * </pre>
   *
   * <code>int32 currentPageIndex = 7;</code>
   * @param value The currentPageIndex to set.
   */
  private void setCurrentPageIndex(int value) {
    
    currentPageIndex_ = value;
  }
  /**
   * <pre>
   * The page index for the current page.
   * </pre>
   *
   * <code>int32 currentPageIndex = 7;</code>
   */
  private void clearCurrentPageIndex() {

    currentPageIndex_ = 0;
  }

  public static final int NEXTPAGEINDEX_FIELD_NUMBER = 8;
  private int nextPageIndex_;
  /**
   * <pre>
   * The page index for the next page. If negative there is no next page
   * </pre>
   *
   * <code>int32 nextPageIndex = 8;</code>
   * @return The nextPageIndex.
   */
  @java.lang.Override
  public int getNextPageIndex() {
    return nextPageIndex_;
  }
  /**
   * <pre>
   * The page index for the next page. If negative there is no next page
   * </pre>
   *
   * <code>int32 nextPageIndex = 8;</code>
   * @param value The nextPageIndex to set.
   */
  private void setNextPageIndex(int value) {
    
    nextPageIndex_ = value;
  }
  /**
   * <pre>
   * The page index for the next page. If negative there is no next page
   * </pre>
   *
   * <code>int32 nextPageIndex = 8;</code>
   */
  private void clearNextPageIndex() {

    nextPageIndex_ = 0;
  }

  public static ai.sensorycloud.api.common.PaginationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.common.PaginationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.common.PaginationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.common.PaginationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.common.PaginationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ai.sensorycloud.api.common.PaginationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ai.sensorycloud.api.common.PaginationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.common.PaginationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ai.sensorycloud.api.common.PaginationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static ai.sensorycloud.api.common.PaginationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.common.PaginationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ai.sensorycloud.api.common.PaginationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.common.PaginationResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A message for the server to tell how the data has been paginated
   * </pre>
   *
   * Protobuf type {@code sensory.api.common.PaginationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ai.sensorycloud.api.common.PaginationResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.common.PaginationResponse)
      ai.sensorycloud.api.common.PaginationResponseOrBuilder {
    // Construct using ai.sensorycloud.api.common.PaginationResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The parameter by which the data has been ordered by
     * </pre>
     *
     * <code>string ordering = 1;</code>
     * @return The ordering.
     */
    @java.lang.Override
    public java.lang.String getOrdering() {
      return instance.getOrdering();
    }
    /**
     * <pre>
     * The parameter by which the data has been ordered by
     * </pre>
     *
     * <code>string ordering = 1;</code>
     * @return The bytes for ordering.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrderingBytes() {
      return instance.getOrderingBytes();
    }
    /**
     * <pre>
     * The parameter by which the data has been ordered by
     * </pre>
     *
     * <code>string ordering = 1;</code>
     * @param value The ordering to set.
     * @return This builder for chaining.
     */
    public Builder setOrdering(
        java.lang.String value) {
      copyOnWrite();
      instance.setOrdering(value);
      return this;
    }
    /**
     * <pre>
     * The parameter by which the data has been ordered by
     * </pre>
     *
     * <code>string ordering = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrdering() {
      copyOnWrite();
      instance.clearOrdering();
      return this;
    }
    /**
     * <pre>
     * The parameter by which the data has been ordered by
     * </pre>
     *
     * <code>string ordering = 1;</code>
     * @param value The bytes for ordering to set.
     * @return This builder for chaining.
     */
    public Builder setOrderingBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOrderingBytes(value);
      return this;
    }

    /**
     * <pre>
     * "True" if the data has been sorted in decending order
     * </pre>
     *
     * <code>bool decending = 2;</code>
     * @return The decending.
     */
    @java.lang.Override
    public boolean getDecending() {
      return instance.getDecending();
    }
    /**
     * <pre>
     * "True" if the data has been sorted in decending order
     * </pre>
     *
     * <code>bool decending = 2;</code>
     * @param value The decending to set.
     * @return This builder for chaining.
     */
    public Builder setDecending(boolean value) {
      copyOnWrite();
      instance.setDecending(value);
      return this;
    }
    /**
     * <pre>
     * "True" if the data has been sorted in decending order
     * </pre>
     *
     * <code>bool decending = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDecending() {
      copyOnWrite();
      instance.clearDecending();
      return this;
    }

    /**
     * <pre>
     * A list of all possible parameters that the data can be ordered by
     * </pre>
     *
     * <code>repeated string possibleOrderings = 3;</code>
     * @return A list containing the possibleOrderings.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getPossibleOrderingsList() {
      return java.util.Collections.unmodifiableList(
          instance.getPossibleOrderingsList());
    }
    /**
     * <pre>
     * A list of all possible parameters that the data can be ordered by
     * </pre>
     *
     * <code>repeated string possibleOrderings = 3;</code>
     * @return The count of possibleOrderings.
     */
    @java.lang.Override
    public int getPossibleOrderingsCount() {
      return instance.getPossibleOrderingsCount();
    }
    /**
     * <pre>
     * A list of all possible parameters that the data can be ordered by
     * </pre>
     *
     * <code>repeated string possibleOrderings = 3;</code>
     * @param index The index of the element to return.
     * @return The possibleOrderings at the given index.
     */
    @java.lang.Override
    public java.lang.String getPossibleOrderings(int index) {
      return instance.getPossibleOrderings(index);
    }
    /**
     * <pre>
     * A list of all possible parameters that the data can be ordered by
     * </pre>
     *
     * <code>repeated string possibleOrderings = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the possibleOrderings at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPossibleOrderingsBytes(int index) {
      return instance.getPossibleOrderingsBytes(index);
    }
    /**
     * <pre>
     * A list of all possible parameters that the data can be ordered by
     * </pre>
     *
     * <code>repeated string possibleOrderings = 3;</code>
     * @param index The index to set the value at.
     * @param value The possibleOrderings to set.
     * @return This builder for chaining.
     */
    public Builder setPossibleOrderings(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setPossibleOrderings(index, value);
      return this;
    }
    /**
     * <pre>
     * A list of all possible parameters that the data can be ordered by
     * </pre>
     *
     * <code>repeated string possibleOrderings = 3;</code>
     * @param value The possibleOrderings to add.
     * @return This builder for chaining.
     */
    public Builder addPossibleOrderings(
        java.lang.String value) {
      copyOnWrite();
      instance.addPossibleOrderings(value);
      return this;
    }
    /**
     * <pre>
     * A list of all possible parameters that the data can be ordered by
     * </pre>
     *
     * <code>repeated string possibleOrderings = 3;</code>
     * @param values The possibleOrderings to add.
     * @return This builder for chaining.
     */
    public Builder addAllPossibleOrderings(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllPossibleOrderings(values);
      return this;
    }
    /**
     * <pre>
     * A list of all possible parameters that the data can be ordered by
     * </pre>
     *
     * <code>repeated string possibleOrderings = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPossibleOrderings() {
      copyOnWrite();
      instance.clearPossibleOrderings();
      return this;
    }
    /**
     * <pre>
     * A list of all possible parameters that the data can be ordered by
     * </pre>
     *
     * <code>repeated string possibleOrderings = 3;</code>
     * @param value The bytes of the possibleOrderings to add.
     * @return This builder for chaining.
     */
    public Builder addPossibleOrderingsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addPossibleOrderingsBytes(value);
      return this;
    }

    /**
     * <pre>
     * The total count of data objects
     * </pre>
     *
     * <code>int64 totalCount = 4;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public long getTotalCount() {
      return instance.getTotalCount();
    }
    /**
     * <pre>
     * The total count of data objects
     * </pre>
     *
     * <code>int64 totalCount = 4;</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(long value) {
      copyOnWrite();
      instance.setTotalCount(value);
      return this;
    }
    /**
     * <pre>
     * The total count of data objects
     * </pre>
     *
     * <code>int64 totalCount = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      copyOnWrite();
      instance.clearTotalCount();
      return this;
    }

    /**
     * <pre>
     * The page size of the data
     * </pre>
     *
     * <code>int32 pageSize = 5;</code>
     * @return The pageSize.
     */
    @java.lang.Override
    public int getPageSize() {
      return instance.getPageSize();
    }
    /**
     * <pre>
     * The page size of the data
     * </pre>
     *
     * <code>int32 pageSize = 5;</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(int value) {
      copyOnWrite();
      instance.setPageSize(value);
      return this;
    }
    /**
     * <pre>
     * The page size of the data
     * </pre>
     *
     * <code>int32 pageSize = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      copyOnWrite();
      instance.clearPageSize();
      return this;
    }

    /**
     * <pre>
     * The page index for the previous page. If negative there is no previous page
     * </pre>
     *
     * <code>int32 prevPageIndex = 6;</code>
     * @return The prevPageIndex.
     */
    @java.lang.Override
    public int getPrevPageIndex() {
      return instance.getPrevPageIndex();
    }
    /**
     * <pre>
     * The page index for the previous page. If negative there is no previous page
     * </pre>
     *
     * <code>int32 prevPageIndex = 6;</code>
     * @param value The prevPageIndex to set.
     * @return This builder for chaining.
     */
    public Builder setPrevPageIndex(int value) {
      copyOnWrite();
      instance.setPrevPageIndex(value);
      return this;
    }
    /**
     * <pre>
     * The page index for the previous page. If negative there is no previous page
     * </pre>
     *
     * <code>int32 prevPageIndex = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrevPageIndex() {
      copyOnWrite();
      instance.clearPrevPageIndex();
      return this;
    }

    /**
     * <pre>
     * The page index for the current page.
     * </pre>
     *
     * <code>int32 currentPageIndex = 7;</code>
     * @return The currentPageIndex.
     */
    @java.lang.Override
    public int getCurrentPageIndex() {
      return instance.getCurrentPageIndex();
    }
    /**
     * <pre>
     * The page index for the current page.
     * </pre>
     *
     * <code>int32 currentPageIndex = 7;</code>
     * @param value The currentPageIndex to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentPageIndex(int value) {
      copyOnWrite();
      instance.setCurrentPageIndex(value);
      return this;
    }
    /**
     * <pre>
     * The page index for the current page.
     * </pre>
     *
     * <code>int32 currentPageIndex = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentPageIndex() {
      copyOnWrite();
      instance.clearCurrentPageIndex();
      return this;
    }

    /**
     * <pre>
     * The page index for the next page. If negative there is no next page
     * </pre>
     *
     * <code>int32 nextPageIndex = 8;</code>
     * @return The nextPageIndex.
     */
    @java.lang.Override
    public int getNextPageIndex() {
      return instance.getNextPageIndex();
    }
    /**
     * <pre>
     * The page index for the next page. If negative there is no next page
     * </pre>
     *
     * <code>int32 nextPageIndex = 8;</code>
     * @param value The nextPageIndex to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageIndex(int value) {
      copyOnWrite();
      instance.setNextPageIndex(value);
      return this;
    }
    /**
     * <pre>
     * The page index for the next page. If negative there is no next page
     * </pre>
     *
     * <code>int32 nextPageIndex = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextPageIndex() {
      copyOnWrite();
      instance.clearNextPageIndex();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sensory.api.common.PaginationResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ai.sensorycloud.api.common.PaginationResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "ordering_",
            "decending_",
            "possibleOrderings_",
            "totalCount_",
            "pageSize_",
            "prevPageIndex_",
            "currentPageIndex_",
            "nextPageIndex_",
          };
          java.lang.String info =
              "\u0000\b\u0000\u0000\u0001\b\b\u0000\u0001\u0000\u0001\u0208\u0002\u0007\u0003\u021a" +
              "\u0004\u0002\u0005\u0004\u0006\u0004\u0007\u0004\b\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ai.sensorycloud.api.common.PaginationResponse> parser = PARSER;
        if (parser == null) {
          synchronized (ai.sensorycloud.api.common.PaginationResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ai.sensorycloud.api.common.PaginationResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sensory.api.common.PaginationResponse)
  private static final ai.sensorycloud.api.common.PaginationResponse DEFAULT_INSTANCE;
  static {
    PaginationResponse defaultInstance = new PaginationResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PaginationResponse.class, defaultInstance);
  }

  public static ai.sensorycloud.api.common.PaginationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PaginationResponse> PARSER;

  public static com.google.protobuf.Parser<PaginationResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

